// M2.3: solo PostgreSQL isolato; nessun accesso/credenziale Production.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net'),{spawnSync}=require('node:child_process'),{randomUUID,createHash}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite'),{fixture,A,B,OP,OP2,RAP,V,USER,TOKEN}=require('./fixtureStep3.cjs');
const dir=path.resolve(__dirname,'../../../supabase/migrations'),read=n=>fs.readFileSync(path.join(dir,n),'utf8');
const sql=read('20261006_rapportino_materiali_writer.sql'),call='SELECT public.salva_rapportino_con_prestazioni($1::jsonb,$2) v';
const empty=()=>({nuove:[],aggiornate:[],rimosse:[]});
const material=(extra={})=>({materiale_id:null,chiave_client:randomUUID(),descrizione:'Collante',unita_misura:'sacco',quantita:'2.500000',costo_unitario:null,note:'',...extra});
const prest=(extra={})=>({prestazione_id:null,chiave_client:randomUUID(),operaio_id:OP,ora_inizio:'08:00',ora_fine:'12:00',pausa_minuti:0,lavoro_in_economia:false,variante_id:null,...extra});
const payload=(extra={})=>({versione_contratto:2,richiesta_id:randomUUID(),rapportino_id:null,revisione_attesa:null,cantiere_id:A,data:'2026-10-06',documento:{note:'Lavori'},prestazioni:empty(),materiali:empty(),...extra});
async function setup(db){await db.exec(fixture);await db.exec(`ALTER TABLE public.rapportini ADD COLUMN costo_materiali text; UPDATE public.rapportini SET materiali='Legacy materiali',quantita_materiali='Legacy quantità',costo_materiali='Non numerico';`);for(const n of ['20261003_rapportino_prestazioni_step2.sql','20261003_rapportino_servizio_step3.sql','20261003_rapportino_backend_pooler.sql','20261004_rapportino_lettura_portale.sql','20261006_rapportino_materiali_schema.sql'])await db.exec(read(n));await db.query('SELECT public.crea_sessione_rapportino($1,$2)',['1234',TOKEN]);}
const write=async(db,p,token=TOKEN)=>(await db.query(call,[JSON.stringify(p),token])).rows[0].v;
const edit=(r,extra={})=>payload({rapportino_id:r.rapportino_id,revisione_attesa:r.revisione,data:r.data,cantiere_id:r.cantiere_id,documento:{},...extra});
const rowPayload=m=>({materiale_id:m.materiale_id,chiave_client:m.chiave_client,descrizione:m.descrizione,unita_misura:m.unita_misura,quantita:m.quantita,costo_unitario:m.costo_unitario,note:m.note});
const reject=(f,code)=>assert.rejects(f,e=>e.code===code);
async function snapshot(db){const out={};for(const t of ['rapportini','rapportino_prestazioni','rapportino_materiali','timbrature','artecna_rapportini.richieste'])out[t]=(await db.query(`SELECT to_jsonb(t) v FROM ${t} t ORDER BY to_jsonb(t)::text`)).rows;return out;}

test('M2.3: contratti, materiali, atomicità, sicurezza e baseline',async t=>{
 const db=new PGlite();try{
 await setup(db);const v1=payload({versione_contratto:1,documento:{note:'Storico',materiali:'Vecchio testo',quantita_materiali:'Due sacchi'},prestazioni:{...empty(),nuove:[prest()]}});delete v1.materiali;
 const before=await write(db,v1),oldFn=(await db.query(`SELECT prosrc FROM pg_proc WHERE oid='public.salva_rapportino_con_prestazioni(jsonb,text)'::regprocedure`)).rows[0].prosrc;
 await db.exec(sql);let current;
 const run=(name,f)=>t.test(name,f);
 await run('baseline contratto 1 fingerprint e helper prestazioni storico invariato',async()=>{const s=(await db.query(`SELECT prosrc FROM pg_proc WHERE oid='artecna_rapportini.salva_contratto_uno(jsonb,text)'::regprocedure`)).rows[0].prosrc;assert.equal(s,oldFn);assert.equal(createHash('sha256').update(s.replace(/\r\n/g,'\n')).digest('hex'),createHash('sha256').update(oldFn.replace(/\r\n/g,'\n')).digest('hex'));});
 await run('core Prestazioni contratto 2 conserva esattamente corpo operativo storico',async()=>{const p=(await db.query(`SELECT prosrc FROM pg_proc WHERE oid='artecna_rapportini.applica_prestazioni_rapportino(jsonb)'::regprocedure`)).rows[0].prosrc.replace(/\r\n/g,'\n'),core=(await db.query(`SELECT prosrc FROM pg_proc WHERE oid='artecna_rapportini.applica_prestazioni_contratto_due(jsonb)'::regprocedure`)).rows[0].prosrc;assert(core.includes(p.slice(p.indexOf('  ops:='),p.indexOf('  IF changed OR ver=0 THEN'))));assert(!core.includes('INSERT INTO artecna_rapportini.richieste'));assert(!core.includes('revisione_prestazioni='));});
 await run('retry storico contratto 1 restituisce risultato completo invariato senza mutazioni',async()=>{const s=await snapshot(db);assert.deepEqual(await write(db,v1),before);assert.deepEqual(await snapshot(db),s);});
 await run('contratto 1 nuovo crea/retry/modifica senza adozione',async()=>{const p={...v1,richiesta_id:randomUUID(),data:'2026-10-07'},r=await write(db,p);assert.deepEqual(await write(db,p),r);const e=edit(r,{versione_contratto:1,documento:{note:'Modifica'}});delete e.materiali;const m=await write(db,e);assert.equal(m.revisione,r.revisione+1);assert.equal((await db.query('SELECT versione_materiali FROM rapportini WHERE id=$1',[r.rapportino_id])).rows[0].versione_materiali,0);});
 await run('nuovo contratto 2 zero materiali: adozione 1, revisione 1, totale 0.00 completa',async()=>{current=await write(db,payload({data:'2026-10-08'}));assert.equal(current.versione_contratto,2);assert.equal(current.versione_materiali,1);assert.equal(current.revisione,1);assert.deepEqual(current.materiali,[]);assert.deepEqual(current.riepilogo_materiali,{totale_materiali_valorizzati:'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true});assert.deepEqual(current.documento,{note:'Lavori'});});
 await run('adozione storica vuota una revisione; legacy materiali/quantità/costo preservati',async()=>{const legacy=(await db.query('SELECT materiali,quantita_materiali,costo_materiali FROM rapportini WHERE id=$1',[before.rapportino_id])).rows[0];const r=await write(db,edit(before));assert.equal(r.revisione,before.revisione+1);assert.equal(r.versione_materiali,1);assert.deepEqual((await db.query('SELECT materiali,quantita_materiali,costo_materiali FROM rapportini WHERE id=$1',[r.rapportino_id])).rows[0],legacy);});
 await run('materiali NULL/zero/positivo e descrizioni identiche sono identità indipendenti',async()=>{current=await write(db,edit(current,{materiali:{...empty(),nuove:[material(),material({costo_unitario:'0.000000'}),material({quantita:'0.750000',costo_unitario:'1.234567'})]}}));assert.equal(current.materiali.length,3);assert.equal(new Set(current.materiali.map(m=>m.materiale_id)).size,3);assert.deepEqual(current.materiali.map(m=>m.costo_totale).sort(),[null,'0.00','0.93'].sort());assert.deepEqual(current.riepilogo_materiali,{totale_materiali_valorizzati:'0.93',numero_materiali_da_valorizzare:1,valorizzazione_completa:false});assert(current.materiali.every(m=>m.revisione===0));});
 await run('retry identico: risultato e DB identici, un solo intento hash intero payload',async()=>{const p=edit(current,{documento:{note:'Test retry'}}),r=await write(db,p),s=await snapshot(db);assert.deepEqual(await write(db,p),r);assert.deepEqual(await snapshot(db),s);const h=(await db.query(`SELECT encode(payload_sha256,'hex') h FROM artecna_rapportini.richieste WHERE richiesta_id=$1`,[p.richiesta_id])).rows[0].h;const expected=(await db.query(`SELECT encode(sha256(convert_to($1::jsonb::text,'UTF8')),'hex') h`,[JSON.stringify(p)])).rows[0].h;assert.equal(h,expected);await reject(()=>write(db,{...p,materiali:{...empty(),nuove:[material()]}}),'PR409');current=r;});
 await run('nuova chiave già attiva e identica no-op senza incremento',async()=>{const m=current.materiali[0],p=edit(current,{materiali:{...empty(),nuove:[{...rowPayload(m),materiale_id:null}]}}),r=await write(db,p);assert.equal(r.revisione,current.revisione);assert.deepEqual(r.materiali,current.materiali);current=r;});
 await run('aggiornamento effettivo: revisione riga +1 e aggregata +1',async()=>{const m=current.materiali.find(x=>x.costo_unitario===null),r=await write(db,edit(current,{materiali:{...empty(),aggiornate:[{...rowPayload(m),costo_unitario:'3.000000'}]}}));assert.equal(r.revisione,current.revisione+1);const out=r.materiali.find(x=>x.materiale_id===m.materiale_id);assert.equal(out.revisione,m.revisione+1);assert.equal(out.costo_totale,'7.50');assert.equal(r.riepilogo_materiali.valorizzazione_completa,true);current=r;});
 await run('update identico no-op: nessuna revisione riga/aggregata',async()=>{const r=await write(db,edit(current,{materiali:{...empty(),aggiornate:[rowPayload(current.materiali[0])]}}));assert.equal(r.revisione,current.revisione);assert.deepEqual(r.materiali,current.materiali);current=r;});
 await run('note + materiale: una sola revisione',async()=>{const r=await write(db,edit(current,{documento:{note:'Note nuove'},materiali:{...empty(),nuove:[material({costo_unitario:'2.000000'})]}}));assert.equal(r.revisione,current.revisione+1);current=r;});
 await run('prestazione + materiale: una sola revisione e timbratura coerente',async()=>{const r=await write(db,edit(current,{prestazioni:{...empty(),nuove:[prest()]},materiali:{...empty(),nuove:[material()]}}));assert.equal(r.revisione,current.revisione+1);assert.equal((await db.query('SELECT count(*) n FROM timbrature WHERE rapportino_id=$1',[r.rapportino_id])).rows[0].n,1);current=r;});
 await run('documento + prestazione + tre materiali: una sola revisione',async()=>{const r=await write(db,edit(current,{documento:{note:'Tre righe'},prestazioni:{...empty(),nuove:[prest({operaio_id:OP2})]},materiali:{...empty(),nuove:[material(),material(),material()]}}));assert.equal(r.revisione,current.revisione+1);assert.equal(r.prestazioni.length,2);current=r;});
 await run('prestazioni Economia/Variante e fotografia costo/proiezione conservate',async()=>{const r=await write(db,edit(current,{prestazioni:{...empty(),nuove:[prest({lavoro_in_economia:true,variante_id:V}),prest({lavoro_in_economia:true,variante_id:null})]}}));assert(r.prestazioni.some(p=>p.variante_id===V));assert(r.prestazioni.some(p=>p.lavoro_in_economia&&p.variante_id===null));const rows=(await db.query('SELECT costo_orario_interno_storico FROM rapportino_prestazioni WHERE rapportino_id=$1',[r.rapportino_id])).rows;assert(rows.every(x=>Number(x.costo_orario_interno_storico)>=0));current=r;});
 await run('prestazione update/rimozione mantiene regole, ore e timbrature',async()=>{const p=current.prestazioni[0],r=await write(db,edit(current,{prestazioni:{...empty(),aggiornate:[{...prest(),prestazione_id:p.prestazione_id,chiave_client:p.chiave_client,ora_fine:'13:00'}],rimosse:[current.prestazioni[1].prestazione_id]}}));assert.equal(r.revisione,current.revisione+1);assert.equal(r.prestazioni.find(x=>x.prestazione_id===p.prestazione_id).ore,5);assert.equal((await db.query('SELECT count(*) n FROM timbrature WHERE rapportino_id=$1',[r.rapportino_id])).rows[0].n,3);current=r;});
 await run('rimozione materiale tombstone, revisione +1, esclusione totale',async()=>{const m=current.materiali.find(x=>x.costo_totale==='7.50'),r=await write(db,edit(current,{materiali:{...empty(),rimosse:[m.materiale_id]}}));const out=r.materiali.find(x=>x.materiale_id===m.materiale_id);assert(out.rimossa_at);assert.equal(out.revisione,m.revisione+1);assert.equal(r.revisione,current.revisione+1);current=r;});
 await run('tombstone non riattivabile e rimozione ripetuta rifiutata',async()=>{const m=current.materiali.find(x=>x.rimossa_at);await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[{...rowPayload(m),materiale_id:null}]}})),'PR409');await reject(()=>write(db,edit(current,{materiali:{...empty(),rimosse:[m.materiale_id]}})),'22023');await reject(()=>write(db,edit(current,{materiali:{...empty(),aggiornate:[rowPayload(m)]}})),'22023');});
 await run('stessa chiave con dati diversi conflitto',async()=>{const m=current.materiali.find(x=>!x.rimossa_at);await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[{...rowPayload(m),materiale_id:null,note:'Diversa'}]}})),'PR409');});
 await run('identità chiave immutabile su update',async()=>{const m=current.materiali.find(x=>!x.rimossa_at);await reject(()=>write(db,edit(current,{materiali:{...empty(),aggiornate:[{...rowPayload(m),chiave_client:randomUUID()}]}})),'PR403');});
 await run('materiale altro Rapportino negato',async()=>{const r=await write(db,payload({data:'2026-10-09',materiali:{...empty(),nuove:[material()]}}));await reject(()=>write(db,edit(current,{materiali:{...empty(),aggiornate:[rowPayload(r.materiali[0])]}})),'22023');});
 for(const bad of ['1','1.0','01.000000','-1.000000','1.0000001','1000000000000.000000','1e2','NaN','Infinity','1,000000',1,null,'0.000000'])await run('quantità non canonica/range '+String(bad),async()=>{await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[material({quantita:bad})]}})),'22023');});
 for(const bad of ['-1.000000','0','0.0000001','1000000000000.000000','NaN',0])await run('costo non canonico/range '+String(bad),async()=>{await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[material({costo_unitario:bad})]}})),'22023');});
 for(const bad of ['invalid',randomUUID().toUpperCase(),'{'+randomUUID()+'}'])await run('chiave client non canonica '+bad.slice(0,8),async()=>{await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[material({chiave_client:bad})]}})),'22023');});
 for(const field of ['materiali','quantita_materiali','costo_materiali'])await run('documento V2 vieta '+field,async()=>{await reject(()=>write(db,edit(current,{documento:{[field]:'Client'}})),'22023');});
 await run('envelope extra, totale client, categoria mancante, >100, UUID errato rifiutati',async()=>{await reject(()=>write(db,{...edit(current),extra:true}),'22023');await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:[material({costo_totale:'100'})]}})),'22023');await reject(()=>write(db,edit(current,{materiali:{nuove:[],aggiornate:[]}})),'22023');await reject(()=>write(db,edit(current,{materiali:{...empty(),nuove:Array.from({length:101},()=>material())}})),'22023');await reject(()=>write(db,edit(current,{materiali:{...empty(),rimosse:['bad']}})),'22023');});
 await run('rollback materiale invalido dopo prestazione valida/include note e adozione',async()=>{const s=await snapshot(db);await reject(()=>write(db,edit(current,{documento:{note:'NON SALVARE'},prestazioni:{...empty(),nuove:[prest()]},materiali:{...empty(),nuove:[material({quantita:'0.000000'})]}})),'22023');assert.deepEqual(await snapshot(db),s);});
 await run('prestazione invalida con materiale valido: nessuna mutazione',async()=>{const s=await snapshot(db);await reject(()=>write(db,edit(current,{prestazioni:{...empty(),nuove:[prest({ora_fine:'07:00'})]},materiali:{...empty(),nuove:[material()]}})),'22023');assert.deepEqual(await snapshot(db),s);});
 await run('errore proiezione dopo prestazioni e materiali applicati: rollback intero intento',async()=>{const s=await snapshot(db);await db.exec(`CREATE FUNCTION public.test_m23_proiezione() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Errore fixture proiezione'; END; $$; CREATE TRIGGER test_m23_proiezione AFTER INSERT ON public.timbrature FOR EACH ROW EXECUTE FUNCTION public.test_m23_proiezione()`);try{await reject(()=>write(db,edit(current,{documento:{note:'NON SALVARE'},prestazioni:{...empty(),nuove:[prest()]},materiali:{...empty(),nuove:[material()]}})),'22023');assert.deepEqual(await snapshot(db),s);}finally{await db.exec('DROP TRIGGER test_m23_proiezione ON public.timbrature; DROP FUNCTION public.test_m23_proiezione()');}});
 await run('revisione obsoleta PR412, nessun merge',async()=>{await reject(()=>write(db,edit(current,{revisione_attesa:current.revisione-1})),'PR412');});
 await run('adozione fallita: padre resta versione 0, prestazioni/note/legacy invariati',async()=>{const p={...v1,richiesta_id:randomUUID(),data:'2026-10-20'},r=await write(db,p),s=await snapshot(db);await reject(()=>write(db,edit(r,{documento:{note:'Non deve restare'},prestazioni:{...empty(),nuove:[prest()]},materiali:{...empty(),nuove:[material({costo_unitario:'NaN'})]}})),'22023');assert.deepEqual(await snapshot(db),s);assert.equal((await db.query('SELECT versione_materiali FROM rapportini WHERE id=$1',[r.rapportino_id])).rows[0].versione_materiali,0);});
 await run('nuova testata con materiale invalido: nessuna creazione parziale',async()=>{const s=await snapshot(db);await reject(()=>write(db,payload({data:'2026-10-21',prestazioni:{...empty(),nuove:[prest()]},materiali:{...empty(),nuove:[material({quantita:'0.000000'})]}})),'22023');assert.deepEqual(await snapshot(db),s);});
 await run('massimo 100 nuove valido e totale stringa esatto; 101 negato',async()=>{const r=await write(db,payload({data:'2026-10-22',materiali:{...empty(),nuove:Array.from({length:100},()=>material({quantita:'1.000000',costo_unitario:'0.010000'}))}}));assert.equal(r.materiali.length,100);assert.equal(r.riepilogo_materiali.totale_materiali_valorizzati,'1.00');});
 await run('V0 non convertito dal contratto 2',async()=>{await reject(()=>write(db,payload({rapportino_id:RAP,revisione_attesa:0,data:'2026-09-21'})),'PR409');});
 await run('rimozione ultima riga: tombstone conservato e riepilogo zero completo',async()=>{const p=payload({data:'2026-10-23',materiali:{...empty(),nuove:[material()]}}),r=await write(db,p),e=edit(r,{materiali:{...empty(),rimosse:[r.materiali[0].materiale_id]}}),out=await write(db,e);assert(out.materiali[0].rimossa_at);assert.deepEqual(out.riepilogo_materiali,{totale_materiali_valorizzati:'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true});const s=await snapshot(db);assert.deepEqual(await write(db,e),out);assert.deepEqual(await snapshot(db),s);});
 await run('contratto 1 dopo adozione preserva materiali/marcatore/costo e risposta V1',async()=>{const rows=(await db.query('SELECT to_jsonb(m) v FROM rapportino_materiali m WHERE rapportino_id=$1 ORDER BY id',[current.rapportino_id])).rows;const p=edit(current,{versione_contratto:1,documento:{note:'Contratto uno'}});delete p.materiali;const r=await write(db,p);assert.equal(r.versione_contratto,1);assert.equal(r.materiali,undefined);assert.deepEqual((await db.query('SELECT to_jsonb(m) v FROM rapportino_materiali m WHERE rapportino_id=$1 ORDER BY id',[current.rapportino_id])).rows,rows);assert.equal((await db.query('SELECT versione_materiali FROM rapportini WHERE id=$1',[current.rapportino_id])).rows[0].versione_materiali,1);});
 await run('RLS/ACL: nessun DML/SELECT/helper per browser,backend,service_role',async()=>{for(const role of ['anon','authenticated','service_role','artecna_rapportini_backend']){assert.equal((await db.query(`SELECT has_table_privilege($1,'public.rapportino_materiali','SELECT,INSERT,UPDATE,DELETE') p`,[role])).rows[0].p,false);await db.exec('SET ROLE '+role);await reject(()=>db.query('SELECT * FROM rapportino_materiali'),'42501');await reject(()=>db.query('SELECT artecna_rapportini.applica_materiali_contratto_due($1,$2)',[current.rapportino_id,empty()]),'42501');await db.exec('RESET ROLE');}});
 await run('DML postgres e DELETE fisico ancora negati senza flag/bypass',async()=>{await reject(()=>db.query(`UPDATE rapportino_materiali SET note='Bypass' WHERE rimossa_at IS NULL`),'PR403');await reject(()=>db.query('DELETE FROM rapportino_materiali'),'PR403');});
 await run('backend dedicato con sessione funziona; senza sessione negato',async()=>{await db.exec('SET SESSION AUTHORIZATION artecna_rapportini_backend');try{const r=await write(db,payload({data:'2026-10-10'}));assert.equal(r.versione_materiali,1);await reject(()=>write(db,payload({data:'2026-10-11'}),null),'42501');}finally{await db.exec('SET SESSION AUTHORIZATION postgres');}});
 await run('desktop authenticated con contesto JWT autorizzato',async()=>{await db.exec(`SELECT set_config('test.user','${USER}',false); SET ROLE authenticated`);try{assert.equal((await write(db,payload({data:'2026-10-12'}),null)).versione_contratto,2);await reject(()=>write(db,payload({cantiere_id:B,data:'2026-10-13'}),null),'42501');}finally{await db.exec('RESET ROLE');}});
 await run('risposta senza costi orari/manodopera, legacy, credenziali/timestamp tecnici',async()=>{const text=JSON.stringify(current);for(const k of ['costo_orario','costo_manodopera','costo_materiali','created_at','updated_at','token_sha256',TOKEN])assert(!text.includes(k));assert.deepEqual(Object.keys(current.documento),['note']);});
 }finally{await db.close();}
});

test('M2.3: PostgreSQL reale concorrenza aggregata e idempotenza',async t=>{
 const {Client}=require('pg'),bin=path.join(os.tmpdir(),'artecna-postgres-test-runtime/pgsql/bin');
 if(!fs.existsSync(path.join(bin,'initdb.exe')))throw new Error('Runtime PostgreSQL locale richiesto');
 const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'artecna-materiali-concorrenza-'));
 const ctl=(exe,args)=>{const r=spawnSync(path.join(bin,exe),args,{stdio:'ignore',windowsHide:true,timeout:30000});if(r.status!==0)throw new Error('Runtime PostgreSQL locale non disponibile');};
 const port=await new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
 const clients=[];let started=false;
 const connect=async(user='postgres')=>{const c=new Client({host:'127.0.0.1',port,database:'postgres',user,connectionTimeoutMillis:5000});await c.connect();clients.push(c);return c;};
 try{
 ctl('initdb.exe',['-D',scratch,'-U','postgres','--auth=trust','--encoding=UTF8','--locale=C']);
 ctl('pg_ctl.exe',['-D',scratch,'-l',path.join(scratch,'server.log'),'-o',`-h 127.0.0.1 -p ${port} -F`,'-w','start']);started=true;
 const admin=await connect(),db={exec:s=>admin.query(s),query:(s,p)=>admin.query(s,p)};await setup(db);await db.exec(sql);
 const a=await connect('artecna_rapportini_backend'),b=await connect('artecna_rapportini_backend');
 let current=await write(a,payload());
 const pids=[(await a.query('SELECT pg_backend_pid() p')).rows[0].p,(await b.query('SELECT pg_backend_pid() p')).rows[0].p];
 const overlap=async(start)=>{await admin.query('BEGIN');let pending;try{pending=start();let both=false;for(let i=0;i<100;i++){const n=(await admin.query("SELECT count(*)::integer n FROM pg_stat_activity WHERE pid=ANY($1::integer[]) AND wait_event_type='Lock'",[pids])).rows[0].n;if(n===2){both=true;break;}await new Promise(r=>setTimeout(r,20));}assert.equal(both,true,'entrambe le connessioni devono essere sovrapposte in attesa lock');}finally{await admin.query('COMMIT');}return pending;};
 await t.test('materiale vs prestazione stessa revisione: un successo, un PR412, nessun merge/deadlock',async()=>{
 const pa=edit(current,{materiali:{...empty(),nuove:[material()]}}),pb=edit(current,{prestazioni:{...empty(),nuove:[prest()]}});
 const results=await overlap(()=>{const lock=admin.query('SELECT id FROM rapportini WHERE id=$1 FOR UPDATE',[current.rapportino_id]);return lock.then(()=>Promise.allSettled([write(a,pa),write(b,pb)]));});
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const bad=results.find(r=>r.status==='rejected');assert.equal(bad.reason.code,'PR412');
 const winner=results.find(r=>r.status==='fulfilled').value;assert.equal(winner.revisione,current.revisione+1);assert.equal(winner.materiali.length+winner.prestazioni.length,1);current=winner;
 });
 await t.test('due retry identici concorrenti: stesso risultato e una sola mutazione/registrazione',async()=>{
 const p=edit(current,{materiali:{...empty(),nuove:[material({costo_unitario:'1.000000'})]}}),oldRev=current.revisione;
 const results=await overlap(()=>{const lock=admin.query("SELECT pg_advisory_xact_lock(hashtextextended('portale'||$1||$2,0))",[OP,p.richiesta_id]);return lock.then(()=>Promise.allSettled([write(a,p),write(b,p)]));});
 assert(results.every(r=>r.status==='fulfilled'));assert.deepEqual(results[0].value,results[1].value);current=results[0].value;assert.equal(current.revisione,oldRev+1);
 assert.equal((await admin.query('SELECT count(*)::integer n FROM artecna_rapportini.richieste WHERE richiesta_id=$1',[p.richiesta_id])).rows[0].n,1);
 });
 await t.test('creazione concorrente stesso giorno: una testata, un PR409',async()=>{
 const pa=payload({data:'2026-10-15'}),pb=payload({data:'2026-10-15'});
 const results=await overlap(()=>{const lock=admin.query("SELECT pg_advisory_xact_lock(hashtextextended('rapportino-giorno:'||$1||$2,0))",[A,pa.data]);return lock.then(()=>Promise.allSettled([write(a,pa),write(b,pb)]));});
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'PR409');assert.equal((await admin.query('SELECT count(*)::integer n FROM rapportini WHERE cantiere_id=$1 AND data=$2',[A,pa.data])).rows[0].n,1);
 });
 }finally{
 await Promise.allSettled(clients.map(c=>c.end()));if(started)ctl('pg_ctl.exe',['-D',scratch,'-m','immediate','-w','stop']);
 const resolved=path.resolve(scratch),root=path.resolve(os.tmpdir())+path.sep;if(!resolved.startsWith(root)||!path.basename(resolved).startsWith('artecna-materiali-concorrenza-'))throw new Error('Percorso cleanup locale inatteso');fs.rmSync(resolved,{recursive:true,force:true});
 }
});

test('M2.3: preflight/post-check fail-closed e rollback installazione',async t=>{
 const variants=[
 ['baseline writer diverge',`CREATE OR REPLACE FUNCTION public.salva_rapportino_con_prestazioni(p_payload jsonb,p_sessione text DEFAULT NULL) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path TO pg_catalog,pg_temp AS $$ SELECT '{}'::jsonb $$`,null],
 ['guardia metadata diverge',`ALTER FUNCTION artecna_rapportini.proteggi_materiale() SECURITY INVOKER`,null],
 ['CHECK quantità indebolito',`ALTER TABLE rapportino_materiali DROP CONSTRAINT rapportino_materiali_quantita_ck; ALTER TABLE rapportino_materiali ADD CONSTRAINT rapportino_materiali_quantita_ck CHECK(quantita>=0)`,null],
 ['indice assente',`DROP INDEX rapportino_materiali_attivi`,null],
 ['ACL browser inattesa',`GRANT SELECT ON rapportino_materiali TO authenticated`,null],
 ['trigger disabilitato',`ALTER TABLE rapportino_materiali DISABLE TRIGGER a_rapportino_materiali_integrita`,null],
 ['default divergente',`ALTER TABLE rapportino_materiali ALTER COLUMN note SET DEFAULT 'Client'`,null],
 ['post-check writer alterato',null,`ALTER FUNCTION artecna_rapportini.salva_contratto_due(jsonb,text) SECURITY INVOKER;`],
 ['post-check grant browser',null,`GRANT INSERT ON public.rapportino_materiali TO authenticated;`],
 ['post-check RLS inattesa',null,`ALTER TABLE public.rapportino_materiali DISABLE ROW LEVEL SECURITY;`],
 ];
 for(const [name,pre,post] of variants)await t.test(name,async()=>{const db=new PGlite();try{await setup(db);if(pre)await db.exec(pre);const state=await snapshot(db),baseline=(await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid IN ('public.salva_rapportino_con_prestazioni(jsonb,text)'::regprocedure,'artecna_rapportini.materiali_fail_closed()'::regprocedure) ORDER BY oid`)).rows;await assert.rejects(()=>db.exec(post?sql.replace('DO $postcheck$',post+'\nDO $postcheck$'):sql));await db.exec('ROLLBACK');assert.deepEqual(await snapshot(db),state);assert.deepEqual((await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid IN ('public.salva_rapportino_con_prestazioni(jsonb,text)'::regprocedure,'artecna_rapportini.materiali_fail_closed()'::regprocedure) ORDER BY oid`)).rows,baseline);assert.equal((await db.query(`SELECT to_regprocedure('artecna_rapportini.salva_contratto_due(jsonb,text)') p`)).rows[0].p,null);}finally{await db.close();}});
});
