// M2.2: solo PostgreSQL isolato. Nessuna credenziale/rete Production.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto')
const {PGlite}=require('@electric-sql/pglite'),{fixture,A,RAP,OP,TOKEN}=require('./fixtureStep3.cjs')
const dir=path.resolve(__dirname,'../../../supabase/migrations'),sql=fs.readFileSync(path.join(dir,'20261006_rapportino_materiali_schema.sql'),'utf8')
async function setup(){const db=new PGlite();await db.exec(fixture);await db.exec(`ALTER TABLE public.rapportini ADD COLUMN costo_materiali text; UPDATE public.rapportini SET materiali='Testo storico',quantita_materiali='Due sacchi',costo_materiali='Costo storico non numerico';`);for(const n of ['20261003_rapportino_prestazioni_step2.sql','20261003_rapportino_servizio_step3.sql','20261003_rapportino_backend_pooler.sql','20261004_rapportino_lettura_portale.sql'])await db.exec(fs.readFileSync(path.join(dir,n),'utf8'));return db}
test('M2.2 schema, guardie, vincoli, ACL e contratto 1 su fixture Production',async t=>{
 const db=await setup(),q=async(s,p=[])=> (await db.query(s,p)).rows,run=(n,f)=>t.test(n,f),reject=(f,c)=>assert.rejects(f,e=>e.code===c)
 const funcs=()=>q(`SELECT oid,to_jsonb(p) v FROM pg_proc p WHERE pronamespace IN ('public'::regnamespace,'artecna_rapportini'::regnamespace) ORDER BY oid`)
 const old=await funcs(),legacy=await q('SELECT id,materiali,quantita_materiali,costo_materiali FROM public.rapportini')
 const insert=async(extra={})=>{const row={rapportino_id:rid,chiave_client:randomUUID(),descrizione:'Collante',unita_misura:'sacco',quantita:'4',costo_unitario:null,...extra},entries=Object.entries(row);return(await q(`INSERT INTO public.rapportino_materiali(${entries.map(([k])=>k)}) VALUES(${entries.map((_,i)=>'$'+(i+1))}) RETURNING *`,entries.map(([,v])=>v)))[0]}
 let rid
 try{
 await db.exec(sql)
 await run('storico resta versione 0, default, legacy preservato e funzioni identiche',async()=>{assert.deepEqual(await q('SELECT id,materiali,quantita_materiali,costo_materiali FROM public.rapportini'),legacy);assert((await q('SELECT versione_materiali FROM public.rapportini')).every(r=>r.versione_materiali===0));assert.deepEqual((await funcs()).filter(r=>old.some(o=>o.oid===r.oid)),old)})
 await run('schema esatto, typmod, nullabilità, generated e default',async()=>{const c=await q(`SELECT attname,format_type(atttypid,atttypmod) tipo,attnotnull,attgenerated FROM pg_attribute WHERE attrelid='public.rapportino_materiali'::regclass AND attnum>0 ORDER BY attnum`);assert.deepEqual(c.map(r=>r.attname),'id rapportino_id chiave_client descrizione unita_misura quantita costo_unitario costo_totale note revisione rimossa_at created_at updated_at'.split(' '));assert.equal(c[5].tipo,'numeric(18,6)');assert.equal(c[7].tipo,'numeric(30,2)');assert.equal(c[7].attgenerated,'s');assert.deepEqual(c.filter(r=>!r.attnotnull).map(r=>r.attname),['costo_unitario','costo_totale','rimossa_at'])})
 await run('PK/FK RESTRICT non deferrable validata, UNIQUE tombstone e indice attivi',async()=>{const c=await q(`SELECT contype,confdeltype,convalidated,condeferrable FROM pg_constraint WHERE conrelid='public.rapportino_materiali'::regclass`);assert.equal(c.filter(r=>r.contype==='p').length,1);assert.equal(c.filter(r=>r.contype==='u').length,1);assert.deepEqual(c.find(r=>r.contype==='f'),{contype:'f',confdeltype:'r',convalidated:true,condeferrable:false});assert.equal((await q(`SELECT pg_get_expr(indpred,indrelid) p FROM pg_index WHERE indexrelid='public.rapportino_materiali_attivi'::regclass`))[0].p,'(rimossa_at IS NULL)')})
 await run('RLS senza policy e nessun privilegio tabella/colonna/browser/backend/dominio',async()=>{assert.equal((await q(`SELECT relrowsecurity FROM pg_class WHERE oid='public.rapportino_materiali'::regclass`))[0].relrowsecurity,true);for(const role of ['anon','authenticated','service_role','artecna_rapportini_backend','artecna_rapportini_rpc']){assert.equal((await q(`SELECT has_table_privilege($1,'public.rapportino_materiali','SELECT,INSERT,UPDATE,DELETE') OR has_any_column_privilege($1,'public.rapportino_materiali','SELECT,INSERT,UPDATE') p`,[role]))[0].p,false);await db.exec(`SET ROLE ${role}`);await reject(()=>q('SELECT * FROM public.rapportino_materiali'),'42501');await db.exec('RESET ROLE')}assert.equal((await q(`SELECT count(*) n FROM pg_policy WHERE polrelid='public.rapportino_materiali'::regclass`))[0].n,0)})
 await run('contratto 1 crea/modifica/retry/rilegge senza materiali o marcatore, costo legacy non scritto',async()=>{await q('SELECT public.crea_sessione_rapportino($1,$2)',['1234',TOKEN]);const p={versione_contratto:1,richiesta_id:randomUUID(),rapportino_id:null,revisione_attesa:null,cantiere_id:A,data:'2026-10-06',documento:{note:'Note',materiali:'Testo V1',quantita_materiali:'Quantità V1'},prestazioni:{nuove:[{prestazione_id:null,chiave_client:randomUUID(),operaio_id:OP,ora_inizio:'08:00',ora_fine:'12:00',pausa_minuti:0,lavoro_in_economia:false,variante_id:null}],aggiornate:[],rimosse:[]}};const write=async p=>(await q('SELECT public.salva_rapportino_con_prestazioni($1::jsonb,$2) v',[JSON.stringify(p),TOKEN]))[0].v;const c=await write(p);rid=c.rapportino_id;assert.deepEqual(await write(p),c);const m=await write({...p,richiesta_id:randomUUID(),rapportino_id:rid,revisione_attesa:c.revisione,documento:{note:'Modificata'},prestazioni:{nuove:[],aggiornate:[],rimosse:[]}});assert.equal(m.revisione,c.revisione+1);await db.exec('SET SESSION AUTHORIZATION artecna_rapportini_backend');let r;try{r=(await q('SELECT public.leggi_rapportino_portale($1,$2,$3,$4) v',[TOKEN,A,p.data,rid]))[0].v}finally{await db.exec('SET SESSION AUTHORIZATION postgres')};assert.equal(r.dettaglio.documento.materiali,'Testo V1');assert.equal((await q('SELECT versione_materiali,costo_materiali FROM public.rapportini WHERE id=$1',[rid]))[0].versione_materiali,0);assert.equal((await q('SELECT count(*) n FROM public.rapportino_materiali'))[0].n,0)})
 await run('versione fuori range e V0 strutturato rifiutati, diretto postgres/browser non adotta',async()=>{await reject(()=>q('UPDATE public.rapportini SET versione_materiali=1 WHERE id=$1',[rid]),'PR403');for(const role of ['anon','authenticated','artecna_rapportini_backend']){await db.exec(`SET ROLE ${role}`);await assert.rejects(()=>q('UPDATE public.rapportini SET versione_materiali=1 WHERE id=$1',[RAP]));await db.exec('RESET ROLE')}
 // Solo laboratorio: privilegi amministrativi temporanei per verificare ramo dominio.
 await db.exec('GRANT UPDATE(versione_materiali),SELECT(versione_materiali) ON public.rapportini TO artecna_rapportini_rpc; SET ROLE artecna_rapportini_rpc');await reject(()=>q('UPDATE public.rapportini SET versione_materiali=2 WHERE id=$1',[rid]),'23514');await reject(()=>q('UPDATE public.rapportini SET versione_materiali=1 WHERE id=$1',[RAP]),'23514');await q('UPDATE public.rapportini SET versione_materiali=1 WHERE id=$1',[rid]);await reject(()=>q('UPDATE public.rapportini SET versione_materiali=0 WHERE id=$1',[rid]),'PR403');await db.exec('RESET ROLE')})
 await run('fail-closed vieta INSERT anche owner; nessun bypass ruolo/GUC',async()=>{await reject(()=>insert(),'PR403');await db.exec("SELECT set_config('artecna.materiali_writer','true',false)");await reject(()=>insert(),'PR403')})
 // Solo laboratorio: si disabilita esclusivamente il veto operativo per provare integrità/CHECK.
 await db.exec('ALTER TABLE public.rapportino_materiali DISABLE TRIGGER z_rapportino_materiali_fail_closed')
 await run('quantità decimale, costo NULL/zero/noto, formula e arrotondamento',async()=>{assert.equal((await insert({quantita:'0.75'})).costo_totale,null);assert.equal((await insert({costo_unitario:'0'})).costo_totale,'0.00');assert.equal((await insert({quantita:'2.5',costo_unitario:'1.234'})).costo_totale,'3.09');await reject(()=>insert({costo_totale:'55'}),'428C9')})
 await run('descrizioni duplicate consentite; chiave unica anche tombstone; PK',async()=>{const key=randomUUID(),a=await insert({chiave_client:key});await insert();await reject(()=>insert({chiave_client:key}),'23505');await q('UPDATE public.rapportino_materiali SET rimossa_at=now() WHERE id=$1',[a.id]);await reject(()=>insert({chiave_client:key}),'23505');await reject(()=>insert({id:a.id}),'23505')})
 await run('padre assente rifiutato dalla guardia prima della FK',async()=>{await assert.rejects(()=>insert({rapportino_id:randomUUID()}),e=>e.code==='PR403'&&e.message==='Rapportino padre assente')})
 await run('FK resta difesa autonoma con guardia disabilitata solo in laboratorio',async()=>{await db.exec('ALTER TABLE public.rapportino_materiali DISABLE TRIGGER a_rapportino_materiali_integrita');try{await reject(()=>insert({rapportino_id:randomUUID()}),'23503')}finally{await db.exec('ALTER TABLE public.rapportino_materiali ENABLE TRIGGER a_rapportino_materiali_integrita')}})
 await run('padre V0 rifiutato dalla guardia',()=>reject(()=>insert({rapportino_id:RAP}),'PR403'))
 await run('padre V1 senza adozione materiali rifiutato',async()=>{const p=randomUUID();await q('INSERT INTO public.rapportini(id,cantiere_id,data,versione_prestazioni) VALUES($1,$2,$3,1)',[p,A,'2026-10-08']);await reject(()=>insert({rapportino_id:p}),'PR403')})
 await run('UUID client canonico validato nativamente e restituito senza conversione',async()=>{const key='12345678-abcd-4abc-8abc-123456789abc',r=await insert({chiave_client:key});assert.equal(r.chiave_client,key);assert.equal((await q('SELECT $1::uuid::text v',[key]))[0].v,key)})
 for(const key of ['12345678abcd4abc8abc123456789abc','{12345678-abcd-4abc-8abc-123456789abc}'])await run('UUID valido ma forma non canonica: '+key,()=>reject(()=>insert({chiave_client:key}),'23514'))
 for(const key of ['non-un-uuid','12345678-abcd-4abc-8abc-123456789abg',' 12345678-abcd-4abc-8abc-123456789abc','12345678-abcd-4abc-8abc-123456789abc '])await run('UUID invalido respinto dal parser: '+key,()=>reject(()=>insert({chiave_client:key}),'22P02'))
 for(const [name,extra,code] of [
 ['chiave non canonica',{chiave_client:randomUUID().toUpperCase()},'23514'],['descrizione vuota',{descrizione:''},'23514'],['descrizione spazi',{descrizione:' Collante'},'23514'],['descrizione lunga',{descrizione:'x'.repeat(2001)},'23514'],['UM vuota',{unita_misura:''},'23514'],['UM spazi',{unita_misura:'kg '},'23514'],['UM lunga',{unita_misura:'x'.repeat(51)},'23514'],['quantità zero',{quantita:'0'},'23514'],['quantità negativa',{quantita:'-1'},'23514'],['quantità NaN',{quantita:'NaN'},'23514'],['quantità infinity',{quantita:'Infinity'},'22003'],['quantità overflow',{quantita:'1000000000000'},'22003'],['costo negativo',{costo_unitario:'-1'},'23514'],['costo NaN',{costo_unitario:'NaN'},'23514'],['costo infinity',{costo_unitario:'Infinity'},'22003'],['note lunghe',{note:'x'.repeat(20001)},'23514']])await run(name,()=>reject(()=>insert(extra),code))
 await run('identità immutabile, revisione/timestamp autorevoli, tombstone e DELETE fisico',async()=>{const a=await insert({revisione:999});assert.equal(a.revisione,0);for(const [field,value] of [['id',randomUUID()],['rapportino_id',RAP],['chiave_client',randomUUID()],['created_at','2000-01-01']])await reject(()=>q(`UPDATE public.rapportino_materiali SET ${field}=$1 WHERE id=$2`,[value,a.id]),'PR403');await q('UPDATE public.rapportino_materiali SET note=$1,revisione=999,updated_at=$2 WHERE id=$3',['Modifica','2000-01-01',a.id]);assert.equal((await q('SELECT revisione FROM public.rapportino_materiali WHERE id=$1',[a.id]))[0].revisione,1);await q('UPDATE public.rapportino_materiali SET rimossa_at=now() WHERE id=$1',[a.id]);await reject(()=>q('UPDATE public.rapportino_materiali SET rimossa_at=NULL WHERE id=$1',[a.id]),'PR403');await reject(()=>q('DELETE FROM public.rapportino_materiali WHERE id=$1',[a.id]),'PR403');await assert.rejects(()=>q('DELETE FROM public.rapportini WHERE id=$1',[rid]),e=>['23503','23001'].includes(e.code))})
 await run('revisione CHECK e limiti massimi ammessi',async()=>{await insert({descrizione:'x'.repeat(2000),unita_misura:'u'.repeat(50),note:'n'.repeat(20000),quantita:'999999999999.999999',costo_unitario:'999999999999.999999'});await db.exec('ALTER TABLE public.rapportino_materiali DISABLE TRIGGER a_rapportino_materiali_integrita');await reject(()=>insert({revisione:-1}),'23514');await db.exec('ALTER TABLE public.rapportino_materiali ENABLE TRIGGER a_rapportino_materiali_integrita')})
 await run('fail-closed UPDATE/DELETE ripristinato; costo_materiali legacy preservato',async()=>{await db.exec('ALTER TABLE public.rapportino_materiali ENABLE TRIGGER z_rapportino_materiali_fail_closed');await reject(()=>q("UPDATE public.rapportino_materiali SET note='vietato' WHERE rimossa_at IS NULL"),'PR403');await reject(()=>q('DELETE FROM public.rapportino_materiali'),'PR403');assert.deepEqual(await q('SELECT id,materiali,quantita_materiali,costo_materiali FROM public.rapportini WHERE id=$1',[RAP]),legacy)})
 await run('FK materiali RESTRICT effettiva su parent senza altre dipendenze',async()=>{
 const parent=randomUUID();await q('INSERT INTO public.rapportini(id,cantiere_id,data,versione_prestazioni) VALUES($1,$2,$3,1)',[parent,A,'2026-10-07']);await db.exec('SET ROLE artecna_rapportini_rpc');await q('UPDATE public.rapportini SET versione_materiali=1 WHERE id=$1',[parent]);await db.exec('RESET ROLE; ALTER TABLE public.rapportino_materiali DISABLE TRIGGER z_rapportino_materiali_fail_closed');await insert({rapportino_id:parent});await assert.rejects(()=>q('DELETE FROM public.rapportini WHERE id=$1',[parent]),e=>['23503','23001'].includes(e.code)&&e.message.includes('rapportino_materiali_rapportino_fk'));await db.exec('ALTER TABLE public.rapportino_materiali ENABLE TRIGGER z_rapportino_materiali_fail_closed')
 })
 await run('contratto 1 su marcatore 1 conserva materiali, revisione e legacy testuale',async()=>{
 const before=await q('SELECT * FROM public.rapportino_materiali ORDER BY id');await q("UPDATE public.rapportini SET costo_materiali='Storico non convertibile' WHERE id=$1",[rid]);const r=(await q('SELECT revisione_prestazioni FROM public.rapportini WHERE id=$1',[rid]))[0];const payload={versione_contratto:1,richiesta_id:randomUUID(),rapportino_id:rid,revisione_attesa:r.revisione_prestazioni,cantiere_id:A,data:'2026-10-06',documento:{note:'Solo documento'},prestazioni:{nuove:[],aggiornate:[],rimosse:[]}};const result=(await q('SELECT public.salva_rapportino_con_prestazioni($1::jsonb,$2) v',[JSON.stringify(payload),TOKEN]))[0].v;assert.equal(result.revisione,Number(r.revisione_prestazioni)+1);assert.equal(result.versione_contratto,1);assert(!('materiali' in result));assert.deepEqual(await q('SELECT * FROM public.rapportino_materiali ORDER BY id'),before);assert.deepEqual((await q('SELECT versione_materiali,costo_materiali FROM public.rapportini WHERE id=$1',[rid]))[0],{versione_materiali:1,costo_materiali:'Storico non convertibile'})
 })
 await run('DML diretto negato ai quattro client',async()=>{for(const role of ['anon','authenticated','service_role','artecna_rapportini_backend']){await db.exec(`SET ROLE ${role}`);await reject(()=>insert(),'42501');await reject(()=>q("UPDATE public.rapportino_materiali SET note='x'"),'42501');await reject(()=>q('DELETE FROM public.rapportino_materiali'),'42501');await db.exec('RESET ROLE')}})
 await run('seconda applicazione rifiutata senza modifiche parziali',async()=>{await assert.rejects(()=>db.exec(sql));await db.exec('ROLLBACK');assert.equal((await q("SELECT count(*) n FROM pg_attribute WHERE attrelid='public.rapportini'::regclass AND attname='versione_materiali' AND NOT attisdropped"))[0].n,1)})
 }finally{await db.close()}
})
test('M2.2 preflight/post-check negativi: rollback completo e storico invariato',async t=>{
 const cases=[['tipo legacy',`ALTER TABLE public.rapportini ALTER COLUMN costo_materiali TYPE integer USING NULL;`,null],['default legacy',`ALTER TABLE public.rapportini ALTER COLUMN costo_materiali SET DEFAULT '0';`,null],['guardia storica metadata',`ALTER FUNCTION artecna_rapportini.proteggi_testata() SECURITY DEFINER;`,null],['RLS',null,'ALTER TABLE public.rapportino_materiali DISABLE ROW LEVEL SECURITY;'],['grant backend',null,'GRANT SELECT ON public.rapportino_materiali TO artecna_rapportini_backend;'],['ACL colonna',null,'GRANT SELECT(descrizione) ON public.rapportino_materiali TO authenticated;'],['trigger disabilitato',null,'ALTER TABLE public.rapportino_materiali DISABLE TRIGGER z_rapportino_materiali_fail_closed;'],['owner',null,'ALTER TABLE public.rapportino_materiali OWNER TO authenticated;'],['formula alterata',null,'ALTER TABLE public.rapportino_materiali DROP COLUMN costo_totale; ALTER TABLE public.rapportino_materiali ADD COLUMN costo_totale numeric(30,2) GENERATED ALWAYS AS (quantita) STORED;']]
 for(const [name,before,inject] of cases)await t.test(name,async()=>{const db=await setup();try{if(before)await db.exec(before);const old=(await db.query(`SELECT oid,prosrc FROM pg_proc WHERE oid='public.salva_rapportino_con_prestazioni(jsonb,text)'::regprocedure`)).rows;const candidate=inject?sql.replace('DO $postcheck$',inject+'\nDO $postcheck$'):sql;await assert.rejects(()=>db.exec(candidate));await db.exec('ROLLBACK');assert.equal((await db.query("SELECT to_regclass('public.rapportino_materiali') t")).rows[0].t,null);assert.equal((await db.query("SELECT count(*) n FROM pg_attribute WHERE attrelid='public.rapportini'::regclass AND attname='versione_materiali' AND NOT attisdropped")).rows[0].n,0);assert.deepEqual((await db.query(`SELECT oid,prosrc FROM pg_proc WHERE oid='public.salva_rapportino_con_prestazioni(jsonb,text)'::regprocedure`)).rows,old)}finally{await db.close()}})
})
