const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),{randomUUID}=require('node:crypto'),{PGlite}=require('@electric-sql/pglite');
const {fixture,A,B,OP,RAP,V,TOKEN}=require('./fixtureStep3.cjs'),dir=path.resolve(__dirname,'../../../supabase/migrations');
const sql=fs.readFileSync(path.join(dir,'20261006_rapportino_materiali_lettura.sql'),'utf8');
async function setup(){const db=new PGlite();await db.exec(fixture);await db.exec(`ALTER TABLE rapportini ADD COLUMN costo_materiali text; UPDATE rapportini SET materiali='Legacy sacchi',quantita_materiali='Due sacchi',costo_materiali='Costo legacy';`);for(const n of ['20261003_rapportino_prestazioni_step2.sql','20261003_rapportino_servizio_step3.sql','20261003_rapportino_backend_pooler.sql','20261004_rapportino_lettura_portale.sql','20261006_rapportino_materiali_schema.sql','20261006_rapportino_materiali_writer.sql'])await db.exec(fs.readFileSync(path.join(dir,n),'utf8'));await db.query('SELECT public.crea_sessione_rapportino($1,$2)',['1234',TOKEN]);return db;}
const empty=()=>({nuove:[],aggiornate:[],rimosse:[]}),mat=(extra={})=>({materiale_id:null,chiave_client:randomUUID(),descrizione:'Sacco',unita_misura:'pz',quantita:'2.500000',costo_unitario:null,note:'',...extra});
const payload=(extra={})=>({versione_contratto:2,richiesta_id:randomUUID(),rapportino_id:null,revisione_attesa:null,cantiere_id:A,data:'2026-10-06',documento:{note:'Note'},prestazioni:empty(),materiali:empty(),...extra});
const write=async(db,p)=>(await db.query('SELECT public.salva_rapportino_con_prestazioni($1::jsonb,$2) v',[JSON.stringify(p),TOKEN])).rows[0].v;
async function read(db,date='2026-10-06',rid=null,version=2,token=TOKEN,c=A){await db.exec('SET SESSION AUTHORIZATION artecna_rapportini_backend');try{return(await db.query(version===undefined?'SELECT public.leggi_rapportino_portale($1,$2,$3,$4) v':'SELECT public.leggi_rapportino_portale($1,$2,$3,$4,$5::smallint) v',version===undefined?[token,c,date,rid]:[token,c,date,rid,version])).rows[0].v;}finally{await db.exec('SET SESSION AUTHORIZATION postgres');}}
async function oldRead(db,date='2026-10-06',rid=null){await db.exec('SET SESSION AUTHORIZATION artecna_rapportini_backend');try{return(await db.query('SELECT public.leggi_rapportino_portale($1,$2,$3,$4) v',[TOKEN,A,date,rid])).rows[0].v;}finally{await db.exec('SET SESSION AUTHORIZATION postgres');}}
function load(file,requires=()=>{throw Error('Import inatteso')}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:requires});return exports;}
const validator1=load('validaLetturaPortale.ts'),validator=load('validaLetturaMateriali.ts',()=>validator1).letturaMaterialiValida;
const rejected=(f,c)=>assert.rejects(f,e=>e.code===c);
test('M2.4 SQL: firma storica, overload, DTO, decimali, legacy e autorizzazione',async t=>{
 const db=await setup();try{
 const v1p=payload({versione_contratto:1,documento:{note:'Giornata',materiali:'Testo storico',quantita_materiali:'Tre sacchi'},prestazioni:{...empty(),nuove:[{prestazione_id:null,chiave_client:randomUUID(),operaio_id:OP,ora_inizio:'08:00',ora_fine:'12:00',pausa_minuti:0,lavoro_in_economia:true,variante_id:V}]}});delete v1p.materiali;
 const historical=await write(db,v1p),before=await oldRead(db),metadata=(await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid IN ('public.leggi_rapportino_portale(text,uuid,date,uuid)'::regprocedure,'artecna_rapportini.autorizza_lettura_portale(text,uuid)'::regprocedure) ORDER BY oid`)).rows;
 await db.exec(sql);let current;
 await t.test('firma/fingerprint/ACL e risposta V1 identici, nessuna chiave Materiali',async()=>{assert.deepEqual((await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid IN ('public.leggi_rapportino_portale(text,uuid,date,uuid)'::regprocedure,'artecna_rapportini.autorizza_lettura_portale(text,uuid)'::regprocedure) ORDER BY oid`)).rows,metadata);assert.deepEqual(await oldRead(db),before);assert.equal(before.dettaglio.materiali,undefined);});
 await t.test('assente V2, senza dettaglio',async()=>{const r=await read(db,'2026-10-07');assert.equal(r.presente,false);assert.equal(r.versione_lettura,2);assert.equal(r.dettaglio,null);assert(validator(r,{cantiere_id:A,data:r.data}));});
 await t.test('V0 riconoscibile, nessuna conversione legacy',async()=>{const r=await read(db,'2026-09-21',RAP);assert.equal(r.versione_prestazioni,0);assert.equal(r.dettaglio,null);assert(validator(r,{cantiere_id:A,data:r.data}));});
 await t.test('V1 storico Materiali 0: testi separati, costo legacy escluso, prestazioni identiche',async()=>{const r=await read(db);assert.equal(r.dettaglio.versione_materiali,0);assert.deepEqual(r.dettaglio.documento_legacy_materiali,{materiali:'Testo storico',quantita_materiali:'Tre sacchi'});assert.deepEqual(r.dettaglio.prestazioni,before.dettaglio.prestazioni);assert.deepEqual(r.dettaglio.materiali,[]);assert.equal(r.dettaglio.revisione,historical.revisione);assert(validator(r,{cantiere_id:A,data:r.data}));});
 await t.test('V1 adottato vuoto: versione 1, zero righe, riepilogo completo',async()=>{current=await write(db,payload({rapportino_id:historical.rapportino_id,revisione_attesa:historical.revisione,documento:{}}));const r=await read(db);assert.equal(r.dettaglio.versione_materiali,1);assert.deepEqual(r.dettaglio.riepilogo_materiali,{totale_materiali_valorizzati:'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true});assert.deepEqual(r.dettaglio.documento_legacy_materiali,{materiali:'Testo storico',quantita_materiali:'Tre sacchi'});});
 const update=async(materiali)=>{current=await write(db,payload({rapportino_id:current.rapportino_id,revisione_attesa:current.revisione,documento:{},materiali}));return read(db);};
 await t.test('più materiali stesso nome, costi NULL/zero/positivo e totali esatti come writer',async()=>{const r=await update({...empty(),nuove:[mat(),mat({costo_unitario:'0.000000'}),mat({quantita:'0.750000',costo_unitario:'1.234567'})]});assert.deepEqual(r.dettaglio.materiali,current.materiali);assert.deepEqual(r.dettaglio.riepilogo_materiali,current.riepilogo_materiali);assert.equal(r.dettaglio.riepilogo_materiali.totale_materiali_valorizzati,'0.93');assert.equal(r.dettaglio.riepilogo_materiali.numero_materiali_da_valorizzare,1);assert(validator(r,{cantiere_id:A,data:r.data}));});
 await t.test('quantità/unitario sei decimali; totale due; nessun number',async()=>{const r=await read(db);for(const m of r.dettaglio.materiali){assert.match(m.quantita,/^[0-9]+\.[0-9]{6}$/);if(m.costo_unitario!==null)assert.match(m.costo_unitario,/^[0-9]+\.[0-9]{6}$/);if(m.costo_totale!==null)assert.match(m.costo_totale,/^[0-9]+\.[0-9]{2}$/);}assert.equal(typeof r.dettaglio.riepilogo_materiali.totale_materiali_valorizzati,'string');});
 await t.test('tombstone incluso, escluso dal totale; identico DTO writer/lettura',async()=>{const m=current.materiali.find(x=>x.costo_totale==='0.93'),r=await update({...empty(),rimosse:[m.materiale_id]});assert(r.dettaglio.materiali.find(x=>x.materiale_id===m.materiale_id).rimossa_at);assert.equal(r.dettaglio.riepilogo_materiali.totale_materiali_valorizzati,'0.00');assert.deepEqual(r.dettaglio.materiali,current.materiali);assert(validator(r,{cantiere_id:A,data:r.data}));});
 await t.test('tutte valorizzate, riepilogo completo',async()=>{const m=current.materiali.find(x=>!x.rimossa_at&&x.costo_unitario===null),{costo_totale,revisione,rimossa_at,...op}=m;await update({...empty(),aggiornate:[{...op,costo_unitario:'2.000000'}]});const r=await read(db);assert.equal(r.dettaglio.riepilogo_materiali.valorizzazione_completa,true);assert.equal(r.dettaglio.riepilogo_materiali.totale_materiali_valorizzati,'5.00');});
 await t.test('ordine deterministico creato_at/id, ripetizione identica',async()=>{const r=await read(db),ids=(await db.query('SELECT id FROM rapportino_materiali WHERE rapportino_id=$1 ORDER BY created_at,id',[current.rapportino_id])).rows.map(x=>x.id);assert.deepEqual(r.dettaglio.materiali.map(x=>x.materiale_id),ids);assert.deepEqual(await read(db),r);});
 await t.test('tutte senza costo: totale 0.00, conteggio N e incomplete',async()=>{const r=await write(db,payload({data:'2026-10-10',materiali:{...empty(),nuove:[mat(),mat()]}})),out=await read(db,r.data,r.rapportino_id);assert.deepEqual(out.dettaglio.riepilogo_materiali,{totale_materiali_valorizzati:'0.00',numero_materiali_da_valorizzare:2,valorizzazione_completa:false});assert(validator(out,{cantiere_id:A,data:r.data}));});
 await t.test('READ ONLY: nessuna mutazione/revisione/sessione, snapshot identico',async()=>{const s=(await db.query('SELECT to_jsonb(r) v FROM rapportini r ORDER BY id')).rows;await db.exec('BEGIN READ ONLY; SET SESSION AUTHORIZATION artecna_rapportini_backend');try{await db.query('SELECT public.leggi_rapportino_portale($1,$2,$3,$4,2::smallint)',[TOKEN,A,'2026-10-06',current.rapportino_id]);}finally{await db.exec('SET SESSION AUTHORIZATION postgres; COMMIT');}assert.deepEqual((await db.query('SELECT to_jsonb(r) v FROM rapportini r ORDER BY id')).rows,s);});
 for(const v of [null,0,1,3])await t.test('versione non supportata '+v,()=>rejected(()=>read(db,'2026-10-06',null,v),'22023'));
 await t.test('UUID/data/cantiere incoerenti e sessione invalida',async()=>{await rejected(()=>read(db,'2026-10-07',current.rapportino_id),'PR409');await rejected(()=>read(db,'2026-10-06',RAP),'PR409');await rejected(()=>read(db,'2026-10-06',null,2,'bad'),'PR401');await rejected(()=>read(db,'2026-10-06',null,2,TOKEN,B),'42501');});
 await t.test('ACL esclusivamente backend, nessun default, browser/service negati',async()=>{const p=(await db.query(`SELECT pronargdefaults,provolatile,prosecdef FROM pg_proc WHERE oid='public.leggi_rapportino_portale(text,uuid,date,uuid,smallint)'::regprocedure`)).rows[0];assert.deepEqual(p,{pronargdefaults:0,provolatile:'s',prosecdef:true});for(const role of ['anon','authenticated','service_role']){assert.equal((await db.query(`SELECT has_function_privilege($1,'public.leggi_rapportino_portale(text,uuid,date,uuid,smallint)','EXECUTE') p`,[role])).rows[0].p,false);}assert.equal((await db.query(`SELECT has_table_privilege('artecna_rapportini_backend','public.rapportino_materiali','SELECT,INSERT,UPDATE,DELETE') p`)).rows[0].p,false);});
 await t.test('DTO non espone costo legacy/interni/timestamp tecnici',async()=>{const s=JSON.stringify(await read(db));for(const k of ['costo_materiali','costo_orario','costo_manodopera','created_at','updated_at',TOKEN])assert(!s.includes(k));});
 }finally{await db.close();}
});

test('M2.4 preflight/post-check: divergenze rifiutate e rollback completo',async t=>{
 const cases=[
 ['lettura V1 baseline divergente',`ALTER FUNCTION public.leggi_rapportino_portale(text,uuid,date,uuid) VOLATILE`,null],
 ['writer M2.3 divergente',`ALTER FUNCTION artecna_rapportini.salva_contratto_due(jsonb,text) SECURITY INVOKER`,null],
 ['schema materiali divergente',`ALTER TABLE rapportino_materiali ALTER COLUMN note TYPE varchar(20000)`,null],
 ['backend con SELECT',`GRANT SELECT ON rapportino_materiali TO artecna_rapportini_backend`,null],
 ['overload default non autorizzato',null,`ALTER FUNCTION public.leggi_rapportino_portale(text,uuid,date,uuid,smallint) VOLATILE;`],
 ['ACL authenticated aggiunta',null,`GRANT EXECUTE ON FUNCTION public.leggi_rapportino_portale(text,uuid,date,uuid,smallint) TO authenticated;`],
 ['schema alterato dopo preflight',null,`ALTER TABLE rapportino_materiali DISABLE ROW LEVEL SECURITY;`],
 ['mutazione dati dopo preflight',null,`UPDATE public.rapportini SET note='Modificata' WHERE id='${RAP}';`],
 ];
 for(const [name,pre,post] of cases)await t.test(name,async()=>{const db=await setup();try{if(pre)await db.exec(pre);const original=(await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid='public.leggi_rapportino_portale(text,uuid,date,uuid)'::regprocedure`)).rows,rows=(await db.query('SELECT to_jsonb(r) v FROM rapportini r ORDER BY id')).rows;await assert.rejects(()=>db.exec(post?sql.replace('DO $postcheck$',post+'\nDO $postcheck$'):sql));await db.exec('ROLLBACK');assert.equal((await db.query(`SELECT to_regprocedure('public.leggi_rapportino_portale(text,uuid,date,uuid,smallint)') p`)).rows[0].p,null);assert.deepEqual((await db.query(`SELECT to_jsonb(p) v FROM pg_proc p WHERE oid='public.leggi_rapportino_portale(text,uuid,date,uuid)'::regprocedure`)).rows,original);assert.deepEqual((await db.query('SELECT to_jsonb(r) v FROM rapportini r ORDER BY id')).rows,rows);}finally{await db.close();}});
});
