const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript')
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',R='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',M='cccccccc-cccc-4ccc-8ccc-cccccccccccc',K='dddddddd-dddd-4ddd-8ddd-dddddddddddd',W='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',D='2026-10-06'
const plain=x=>JSON.parse(JSON.stringify(x)),cache=new Map()
function load(file){file=path.resolve(__dirname,file);if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2017}}).outputText,{exports,require:n=>load(path.resolve(path.dirname(file),n)+'.ts')});return exports}
const mat=load('materialiBozzaV1.ts'),boz=load('bozzaRapportinoV1.ts'),save=load('salvataggioBozzaV1.ts')
const row=(more={})=>({materiale_id:M,chiave_client:K,descrizione:'Cemento',unita_misura:'kg',quantita:'2.500000',costo_unitario:'12.400000',costo_totale:'31.00',note:'',revisione:1,rimossa_at:null,...more})
const details=(versione=1)=>({versione_contratto:2,rapportino_id:R,cantiere_id:A,data:D,revisione:4,documento:{note:'Lavori'},prestazioni:[],versione_materiali:versione,materiali:versione?[row(),row({materiale_id:W,chiave_client:A,rimossa_at:'2026-10-06T12:00:00Z'})]:[],riepilogo_materiali:{totale_materiali_valorizzati:versione?'31.00':'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true},documento_legacy_materiali:{materiali:'Storico',quantita_materiali:'Due sacchi'}})
const vars={cantiere_id:A,stato:'non_caricate',varianti:[]}
const draft=()=>mat.ricostruisciBozzaRapportinoV2(details())

for (const [raw, expected] of [['Collante ', 'Collante'], [' Collante', 'Collante'],
  ['  Collante rapido  ', 'Collante rapido'], [' Collante  rapido ', 'Collante  rapido']]) {
  test('M2.6E trim dominio descrizione ' + JSON.stringify(raw), () => {
    const b=mat.modificaMaterialeBozza(draft(),K,{descrizione:raw,unita_misura:' sacco ',quantita:'2,5',costo_unitario:null,note:' nota '})
    const before=JSON.stringify(b)
    assert.equal(mat.erroriMaterialeBozza(b.materialiStrutturati.righe[0]).length,0)
    assert.equal(save.bozzaV1Salvabile(b,vars),true)
    const r=mat.deltaMaterialiBozza(b).aggiornate[0]
    assert.equal(r.descrizione,expected);assert.equal(r.unita_misura,'sacco')
    assert.equal(r.quantita,'2.500000');assert.equal(r.costo_unitario,null);assert.equal(r.note,' nota ')
    assert.equal(save.creaTentativoSalvataggioV1(b,vars,()=>A).payload.materiali.aggiornate[0].descrizione,expected)
    assert.equal(JSON.stringify(b),before)
  })
}
for (const patch of [{descrizione:'   '},{unita_misura:'   '},{descrizione:' '+ 'x'.repeat(2001)+' '},{unita_misura:' '+ 'x'.repeat(51)+' '}]) {
  test('M2.6E obbligatorietà e limiti dopo trim '+Object.keys(patch)[0]+' '+Object.values(patch)[0].length,()=>{
    const b=mat.modificaMaterialeBozza(draft(),K,patch)
    assert(mat.erroriMaterialeBozza(b.materialiStrutturati.righe[0]).length>0)
    assert.equal(save.bozzaV1Salvabile(b,vars),false);assert.throws(()=>mat.deltaMaterialiBozza(b))
  })
}
test('M2.6E solo spazi esterni su persistente non genera aggiornamenti',()=>{
  const b=mat.modificaMaterialeBozza(draft(),K,{descrizione:' Cemento ',unita_misura:' kg '})
  assert.deepEqual(plain(mat.deltaMaterialiBozza(b)),{nuove:[],aggiornate:[],rimosse:[]})
})
test('M2.5 ricostruzione: baseline immutabile comprende tombstone, attivi editabili e legacy separato',()=>{const b=draft();assert.equal(b.materialiStrutturati.baseline.length,2);assert.equal(b.materialiStrutturati.righe.length,1);assert(Object.isFrozen(b.materialiStrutturati.baseline[0]));assert.deepEqual(plain(b.materialiStrutturati.documento_legacy_materiali),details().documento_legacy_materiali);assert.equal(mat.modificaMaterialeBozza(b,A,{descrizione:'No'}),b);assert.equal(mat.rimuoviMaterialeBozza(b,A),b);assert.deepEqual(plain(mat.deltaMaterialiBozza(b)),{nuove:[],aggiornate:[],rimosse:[]})})
test('M2.5 storico: apertura non adotta; adozione esplicita preserva testi e non converte',()=>{const b=mat.ricostruisciBozzaRapportinoV2(details(0));assert.equal(b.materialiStrutturati.versione_materiali,0);assert.throws(()=>mat.aggiungiMaterialeBozza(b,()=>K));assert.equal(save.creaTentativoSalvataggioV1(b,vars,()=>K).payload.versione_contratto,1);const a=mat.adottaMaterialiStrutturati(b);assert.equal(a.materialiStrutturati.versione_materiali,1);assert.equal(a.materialiStrutturati.righe.length,0);assert.deepEqual(plain(a.documento),plain(b.documento));assert.deepEqual(plain(a.materialiStrutturati.documento_legacy_materiali),plain(b.materialiStrutturati.documento_legacy_materiali));assert.equal(save.creaTentativoSalvataggioV1(a,vars,()=>K).payload.versione_contratto,2)})
test('M2.5 nuove: UUID generato una volta, modifica stabile, stesso nome ammesso, rimozione prima save senza tombstone',()=>{let calls=0,b=mat.aggiungiMaterialeBozza(draft(),()=>{calls++;return R});b=mat.modificaMaterialeBozza(b,R,{descrizione:'Cemento',unita_misura:'kg',quantita:'2',costo_unitario:'0'});assert.equal(calls,1);assert.equal(mat.deltaMaterialiBozza(b).nuove[0].chiave_client,R);assert.equal(mat.deltaMaterialiBozza(b).nuove[0].costo_unitario,'0.000000');b=mat.rimuoviMaterialeBozza(b,R);assert.deepEqual(plain(mat.deltaMaterialiBozza(b)),{nuove:[],aggiornate:[],rimosse:[]});assert.throws(()=>mat.aggiungiMaterialeBozza(b,()=>A))})
test('M2.5 persistenti: confronto canonico, modifica/revert, modifica+rimozione solo UUID',()=>{let b=mat.modificaMaterialeBozza(draft(),K,{quantita:'2,500000',costo_unitario:'12,40'});assert.equal(mat.deltaMaterialiBozza(b).aggiornate.length,0);b=mat.modificaMaterialeBozza(b,K,{quantita:'3'});assert.equal(mat.deltaMaterialiBozza(b).aggiornate.length,1);b=mat.modificaMaterialeBozza(b,K,{quantita:'2,5'});assert.equal(mat.deltaMaterialiBozza(b).aggiornate.length,0);b=mat.modificaMaterialeBozza(b,K,{note:'Nuovo'});b=mat.rimuoviMaterialeBozza(b,K);assert.deepEqual(plain(mat.deltaMaterialiBozza(b)),{nuove:[],aggiornate:[],rimosse:[M]});assert.equal(mat.riepilogoMaterialiBozza(b).totale_materiali_valorizzati,'0.00')})
for(const [input,expected] of [['2','2.000000'],['2,5','2.500000'],['2,500000','2.500000'],['12,40','12.400000'],['0002.5','2.500000'],['999999999999.999999','999999999999.999999']])test('M2.5 decimale '+input,()=>assert.equal(mat.decimaleMateriale(input,true),expected))
for(const input of ['-1','1e2','NaN','Infinity','1,234.50','1.234,50','1,2,3','1.0000001','1000000000000','0','0,000000','','.5','+1'])test('M2.5 decimale rifiutato '+JSON.stringify(input),()=>assert.throws(()=>mat.decimaleMateriale(input,true)))
test('M2.5 costo: vuoto/null sconosciuto, zero distinto, decimale italiano',()=>{assert.equal(mat.costoMateriale(' '),null);assert.equal(mat.costoMateriale(null),null);assert.equal(mat.costoMateriale('0'),'0.000000');assert.equal(mat.costoMateriale('12,40'),'12.400000')})
test('M2.5 preview esatto: mezzo centesimo PostgreSQL, grandi importi, costo NULL e somma per riga',()=>{assert.equal(mat.totaleRigaMateriale('0,005','1'),'0.01');assert.equal(mat.totaleRigaMateriale('0,004999','1'),'0.00');assert.equal(mat.totaleRigaMateriale('999999999999.999999','999999999999.999999'),'999999999999999998000000.00');assert.equal(mat.totaleRigaMateriale('2',null),null);let b=mat.aggiungiMaterialeBozza(draft(),()=>R);b=mat.modificaMaterialeBozza(b,R,{descrizione:'Altro',unita_misura:'kg',quantita:'1'});assert.deepEqual(plain(mat.riepilogoMaterialiBozza(b)),{totale_materiali_valorizzati:'31.00',numero_materiali_da_valorizzare:1,valorizzazione_completa:false});b=mat.modificaMaterialeBozza(b,R,{costo_unitario:'0'});assert.equal(mat.riepilogoMaterialiBozza(b).valorizzazione_completa,true)})
test('M2.5 payload contratto2: chiavi esatte, no costi/totali/revisioni/timestamp/testi legacy, freeze profondo',()=>{const b=mat.modificaMaterialeBozza(draft(),K,{quantita:'3,5'}),t=save.creaTentativoSalvataggioV1(b,vars,()=>K),p=plain(t.payload);assert.equal(p.versione_contratto,2);assert.deepEqual(p.documento,{note:'Lavori'});assert.deepEqual(Object.keys(p.materiali.aggiornate[0]).sort(),['materiale_id','chiave_client','descrizione','unita_misura','quantita','costo_unitario','note'].sort());assert.equal(p.materiali.aggiornate[0].quantita,'3.500000');assert(Object.isFrozen(t.payload.materiali.aggiornate[0]));assert.equal(t.corpo,JSON.stringify(t.payload));assert(!t.corpo.includes('Storico'));assert(!t.corpo.includes('costo_totale'));assert(save.bozzaV1Salvabile(b,vars))})
test('M2.5 nuovo percorso opt-in: contratto2 anche senza materiali, contratto1 operativo invariato',()=>{let b=mat.creaBozzaRapportinoV2(A,D);b=boz.aggiungiPrestazioneBozza(b,'prima');b=boz.modificaPrestazioneBozza(b,'prima',{operaio_id:W,ora_inizio:'08:00',ora_fine:'12:00'});assert.equal(save.creaTentativoSalvataggioV1(b,vars,()=>K).payload.versione_contratto,2);const old=boz.creaBozzaRapportinoV1(A,D);assert(!old.materialiStrutturati);assert.deepEqual(plain(mat.riepilogoMaterialiBozza(b)),{totale_materiali_valorizzati:'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true})})
test('M2.5 integrità: UUID/identità/tombstone/duplicati/campi invalidi bloccano il delta',()=>{for(const patch of [{materiale_id:W},{chiave_client:R},{descrizione:''},{unita_misura:''},{quantita:'0'},{costo_unitario:'-2'}]){const b=draft();b.materialiStrutturati.righe=[{...b.materialiStrutturati.righe[0],...patch}];assert.throws(()=>mat.deltaMaterialiBozza(b));assert.equal(save.bozzaV1Salvabile(b,vars),false)}})

// Riusa il simulatore React U1 esistente, con la sola capability opzionale.
function harness(transport,opt=true){const src=fs.readFileSync(path.join(__dirname,'coordinatoreRapportinoV1.test.cjs'),'utf8').split("test('U1:")[0].replace('ctx,trasporto)','ctx,trasporto,{materiali:__opt})');const sandbox={require,__dirname,Response,AbortController,setTimeout,clearTimeout,setImmediate,console,__opt:opt};vm.runInNewContext(src+'\nglobalThis.__h=harness;',sandbox);return sandbox.__h(transport)}
const flush=()=>new Promise(r=>setImmediate(r))
const read=d=>new Response(JSON.stringify({versione_lettura:2,presente:true,versione_prestazioni:1,rapportino_id:d.rapportino_id,cantiere_id:d.cantiere_id,data:d.data,dettaglio:d}))
function setup(h){h.render().apriNuovoV1();let b=h.bozza.aggiungiPrestazioneBozza(h.render().bozzaV1,'prima');b=h.bozza.modificaPrestazioneBozza(b,'prima',{operaio_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',ora_inizio:'07:00',ora_fine:'12:00'});b=mat.aggiungiMaterialeBozza(b,()=>K);b=mat.modificaMaterialeBozza(b,K,{descrizione:'Cemento',unita_misura:'kg',quantita:'2,5',costo_unitario:'12,40'});h.render().editorProps.onChange(b)}
const authoritative=()=>({...details(),cantiere_id:A,data:'2026-09-30',rapportino_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',materiali:[row()],prestazioni:[]})

test('M2.6E Mobile: spazi accidentali salvabili, payload normalizzato e retry identico',async()=>{
  const calls=[],h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async b=>{calls.push(b);throw Error('Persa')},leggiStatoV2:async()=>read(authoritative())})
  setup(h)
  h.render().editorProps.onChange(mat.modificaMaterialeBozza(h.render().bozzaV1,K,{descrizione:' Collante ',unita_misura:' sacco ',quantita:'2',costo_unitario:null}))
  const before=JSON.stringify(h.render().bozzaV1)
  assert.equal(h.render().editorProps.salvabile,true)
  h.render().editorProps.onSalva();await flush()
  const r=JSON.parse(calls[0]).materiali.nuove[0]
  assert.equal(r.descrizione,'Collante');assert.equal(r.unita_misura,'sacco');assert.equal(r.quantita,'2.000000');assert.equal(r.costo_unitario,null)
  assert.equal(JSON.stringify(h.render().bozzaV1),before)
  h.render().editorProps.onRetry();await flush();assert.equal(calls[0],calls[1]);assert.equal(h.uuid(),1)
})
test('M2.5 coordinatore: successo contratto2, riletturaV2, nuova baseline/delta vuoto, riapertura',async()=>{const calls=[],d=authoritative(),{documento_legacy_materiali,...result}=d;const h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async body=>{calls.push(JSON.parse(body));return new Response(JSON.stringify(result))},leggiStato:async()=>{throw Error('V1 non deve essere chiamato')},leggiStatoV2:async input=>{calls.push(plain(input));return read(d)}});setup(h);h.render().editorProps.onSalva();await flush();assert.equal(calls[0].versione_contratto,2);assert.equal(calls.length,2);assert.equal(h.render().riletturaV1Fallita,false);assert.deepEqual(plain(mat.deltaMaterialiBozza(h.render().bozzaV1)),{nuove:[],aggiornate:[],rimosse:[]});h.render().apriModificaV1();assert.equal(h.render().bozzaV1.materialiStrutturati.righe.length,1)})
test('M2.5 coordinatore: retry identico e modifica materiale invalida intento, nuovo richiesta_id',async()=>{const calls=[],h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async b=>{calls.push(b);throw Error('Persa')},leggiStato:async()=>{throw Error('V1')},leggiStatoV2:async()=>read(authoritative())});setup(h);h.render().editorProps.onSalva();await flush();h.render().editorProps.onRetry();await flush();assert.equal(calls[0],calls[1]);assert.equal(h.uuid(),1);h.render().editorProps.onChange(mat.modificaMaterialeBozza(h.render().bozzaV1,K,{quantita:'3'}));assert.equal(h.render().editorProps.retryDisponibile,false);h.render().editorProps.onSalva();await flush();assert.equal(h.uuid(),2);assert.notEqual(calls[0],calls[2])})
test('M2.5 coordinatore: successo+rilettura fallita non risalva; ripeti controllo autorevole',async()=>{let saves=0,fail=true;const d=authoritative(),{documento_legacy_materiali,...result}=d,h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async()=>{saves++;return new Response(JSON.stringify(result))},leggiStatoV2:async()=>{if(fail)throw Error('Trasporto');return read(d)}});setup(h);h.render().editorProps.onSalva();await flush();assert(h.render().riletturaV1Fallita);assert(h.messaggio().includes('salvato'));assert.equal(h.render().bozzaV1,null);fail=false;await h.render().rileggiSalvatoV1(h.render().salvatoV1,h.ctx.richiestaStato.current);assert.equal(saves,1);assert.equal(h.render().riletturaV1Fallita,false)})
test('M2.5 coordinatore: 409 richiede lettura autorevole, nessun merge delle righe locali',async()=>{const h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async()=>new Response('{}',{status:409}),leggiStatoV2:async()=>read(authoritative())});setup(h);h.render().editorProps.onSalva();await flush();assert(h.render().conflittoV1);const d=authoritative();assert(h.render().riceviLetturaV2(plain({versione_lettura:2,presente:true,versione_prestazioni:1,cantiere_id:d.cantiere_id,data:d.data,rapportino_id:d.rapportino_id,dettaglio:d}),h.ctx.richiestaStato.current));assert.equal(h.render().conflittoV1,false);assert.equal(h.render().bozzaV1.materialiStrutturati.righe[0].quantita,'2.500000')})
for(const campo of ['data','cantiere'])test('M2.5 risposta obsoleta dopo cambio '+campo,async()=>{let finish;const h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:()=>new Promise(r=>finish=r),leggiStatoV2:async()=>read(authoritative())});setup(h);h.render().editorProps.onSalva();h.ctx.richiestaStato.current++;if(campo==='data')h.ctx.dataRapportino='2026-10-01';else h.ctx.cantiereId=R;h.render().invalidaV1();const {documento_legacy_materiali,...result}=authoritative();finish(new Response(JSON.stringify(result)));await flush();assert.equal(h.render().salvatoV1,null);assert.equal(h.render().bozzaV1,null)})
test('M2.5 lettura/apertura non invalida intento congelato e capability non cambia Mobile',async()=>{const h=harness({caricaVarianti:async()=>new Response('[]'),salvaStrutturato:async()=>{throw Error('Persa')},leggiStatoV2:async()=>read(authoritative())});setup(h);h.render().editorProps.onSalva();await flush();assert.equal(h.render().riceviLetturaV2({},h.ctx.richiestaStato.current),false);h.render().apriNuovoV1();assert(h.render().editorProps.retryDisponibile);const page=fs.readFileSync(path.join(__dirname,'../../rapportino/page.tsx'),'utf8');assert(page.includes('trasportoMobileRapportinoConMateriali'));assert(page.includes('materiali: true'));assert(page.includes('riceviLetturaV2'))})
