const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),vm=require('node:vm')
let sequence=0
const load=(file,require)=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require,crypto:{randomUUID:()=>key()}});return exports}
const key=()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`
const util=load(path.resolve(__dirname,'../../utils/rapportinoOperai.ts'),()=>({}))
const model=load(path.join(__dirname,'bozzaRapportinoV1.ts'),()=>util)
const variants=load(path.join(__dirname,'variantiBozzaV1.ts'),()=>({}))
const group=load(path.join(__dirname,'squadraBozzaV1.ts'),()=>model)
const workers=[1,2,3].map(n=>({id:`bbbbbbbb-bbbb-4bbb-8bbb-${String(n).padStart(12,'0')}`,nome:`Operaio ${n}`}))
const site='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',variant='11111111-1111-4111-8111-111111111111'
const cache={cantiere_id:site,stato:'pronte',varianti:[{id:variant,numero:1,etichetta:'Variante',selezionabile:true},{id:site,numero:2,etichetta:'Storica',selezionabile:false}]}
const fresh=()=>model.creaBozzaRapportinoV1(site,'2026-09-30')
const valid=()=>({...group.creaSquadraBozzaV1(),operai:workers.map(o=>o.id),ora_inizio:'07:00',ora_fine:'13:00',pausa_minuti:30})
const nodes=(n,r=[])=>{if(Array.isArray(n))n.forEach(x=>nodes(x,r));else if(n&&n.props){r.push(n);nodes(n.props.children,r)}return r}
function harness(){let state=[],refs=[],cursor=0,rc=0,b=fresh(),disabled=false,v=cache,loads=0,retries=0,changes=0
 const react={useState:init=>{const i=cursor++;if(!(i in state))state[i]=typeof init==='function'?init():init;return[state[i],value=>state[i]=typeof value==='function'?value(state[i]):value]},useRef:init=>{const i=rc++;return refs[i]||(refs[i]={current:init})}}
 const jsx=(type,props)=>({type,props})
 const Panel=load(path.resolve(__dirname,'../../components/RapportinoSquadraV1.tsx'),name=>name==='react'?react:name==='react/jsx-runtime'?{jsx,jsxs:jsx}:name.includes('squadraBozza')?group:variants).default
 const all=()=>{cursor=0;rc=0;return nodes(Panel({bozza:b,operai:workers,varianti:v,disabled,onChange:value=>{b=value;changes++},onRichiediVarianti:()=>loads++,onRiprovaVarianti:()=>retries++}))}
 const button=text=>all().find(n=>n.type==='button'&&n.props.children===text)
 return{all,button,get bozza(){return b},get changes(){return changes},get loads(){return loads},get retries(){return retries},disable:()=>disabled=true,cache:value=>v=value,
 open:()=>button('+ Aggiungi squadra').props.onClick(),prepare:()=>{button('Seleziona tutti').props.onClick();all().filter(n=>n.type==='input'&&n.props.type==='time')[0].props.onChange({target:{value:'07:00'}});all().filter(n=>n.type==='input'&&n.props.type==='time')[1].props.onChange({target:{value:'13:00'}});all().find(n=>n.type==='input'&&n.props.type==='number').props.onChange({target:{value:'30'}})}}
}
test('Squadra UI: apre, selezioni indipendenti, tutti/nessuno, conteggio e annulla senza UUID o modifica',()=>{const h=harness(),before=sequence;h.open();assert(h.all().some(n=>n.type==='fieldset'));assert(h.button('Aggiungi prestazioni').props.disabled);let checks=h.all().filter(n=>n.props.type==='checkbox');checks[0].props.onChange({target:{checked:true}});assert.equal(h.all().filter(n=>n.props.type==='checkbox'&&n.props.checked).length,1);assert(h.button('Aggiungi 1 prestazioni'));h.button('Seleziona tutti').props.onClick();assert.equal(h.all().filter(n=>n.props.type==='checkbox'&&n.props.checked).length,3);h.button('Deseleziona tutti').props.onClick();assert(h.button('Aggiungi prestazioni').props.disabled);h.button('Annulla').props.onClick();assert.equal(h.changes,0);assert.equal(sequence,before);assert(!h.all().some(n=>n.type==='fieldset'));h.open();assert(h.button('Aggiungi prestazioni').props.disabled)})
test('Squadra UI: conferma una sola volta, reset e nessun autosave',()=>{const h=harness();h.open();h.prepare();const before=sequence,confirm=h.button('Aggiungi 3 prestazioni');assert.equal(confirm.props.disabled,false);confirm.props.onClick();confirm.props.onClick();assert.equal(sequence-before,3);assert.equal(h.changes,1);assert.equal(h.bozza.prestazioni.nuove.length,3);assert(!h.all().some(n=>n.type==='fieldset'));h.open();assert(h.button('Aggiungi prestazioni').props.disabled)})
test('Squadra UI: Economia usa callback cache e solo Variante selezionabile; Ordinario resetta',()=>{const h=harness();h.open();h.prepare();h.all().filter(n=>n.props.type==='radio')[1].props.onChange();assert.equal(h.loads,1);assert(h.button('Aggiungi 3 prestazioni').props.disabled);const select=()=>h.all().find(n=>n.type==='select');select().props.onChange({target:{value:site}});assert(h.button('Aggiungi 3 prestazioni').props.disabled);select().props.onChange({target:{value:variant}});assert.equal(h.button('Aggiungi 3 prestazioni').props.disabled,false);h.button('Aggiungi 3 prestazioni').props.onClick();assert(h.bozza.prestazioni.nuove.every(p=>p.lavoro_in_economia&&p.variante_id===variant));h.open();h.prepare();h.all().filter(n=>n.props.type==='radio')[1].props.onChange();select().props.onChange({target:{value:variant}});h.all().filter(n=>n.props.type==='radio')[0].props.onChange();h.button('Aggiungi 3 prestazioni').props.onClick();assert(h.bozza.prestazioni.nuove.slice(3).every(p=>!p.lavoro_in_economia&&p.variante_id===null))})
test('Squadra UI: disabilitazione, cache altro cantiere, errore e retry esistente',()=>{const h=harness();h.open();h.prepare();h.all().filter(n=>n.props.type==='radio')[1].props.onChange();h.cache({...cache,cantiere_id:'altro'});assert(h.button('Aggiungi 3 prestazioni').props.disabled);h.cache({...cache,stato:'errore'});h.button('Riprova varianti').props.onClick();assert.equal(h.retries,1);h.disable();h.button('Annulla').props.onClick();assert(h.all().some(n=>n.type==='fieldset'));h.button('Riprova varianti').props.onClick();assert.equal(h.retries,1)})
for(const change of [{operai:[]},{operai:['inesistente']},{operai:[workers[0].id,workers[0].id]},{ora_inizio:'7:00'},{ora_fine:'07:00'},{ora_fine:'06:00'},{pausa_minuti:-1},{pausa_minuti:360},{pausa_minuti:361},{pausa_minuti:0.5},{pausa_minuti:NaN},{lavoro_in_economia:true,variante_id:null},{lavoro_in_economia:true,variante_id:site}])test(`Squadra validazione negativa ${JSON.stringify(change)}`,()=>{let generated=0;assert.throws(()=>group.aggiungiSquadraBozzaV1(fresh(),{...valid(),...change},workers,cache,()=>{generated++;return key()}));assert.equal(generated,0)})
test('Squadra: tre righe indipendenti, stesso orario/pausa/modalità, UUID distinti e stabili',()=>{let b=group.aggiungiSquadraBozzaV1(fresh(),valid(),workers,cache,key);const rows=b.prestazioni.nuove,keys=rows.map(p=>p.chiave_client);assert.equal(rows.length,3);assert.equal(new Set(keys).size,3);assert(rows.every(p=>p.prestazione_id===null&&p.ora_inizio==='07:00'&&p.ora_fine==='13:00'&&p.pausa_minuti===30&&!p.lavoro_in_economia&&p.variante_id===null));b=model.modificaPrestazioneBozza(b,keys[0],{ora_fine:'14:00'});assert.equal(b.prestazioni.nuove[1].ora_fine,'13:00');assert.equal(b.prestazioni.nuove[0].chiave_client,keys[0]);b=model.rimuoviPrestazioneBozza(b,keys[0]);assert.equal(b.prestazioni.nuove.length,2);assert.equal(b.prestazioni.nuove[0].chiave_client,keys[1])})
test('Squadra: nessuna deduplicazione o controllo sovrapposizione per operaio',()=>{let b=group.aggiungiSquadraBozzaV1(fresh(),valid(),workers,cache,key);b=group.aggiungiSquadraBozzaV1(b,valid(),workers,cache,key);assert.equal(b.prestazioni.nuove.length,6);assert.equal(b.prestazioni.nuove.filter(p=>p.operaio_id===workers[0].id).length,2)})
test('Squadra: V1 persistito conserva baseline/documento/aggiornate/rimosse; solo nuove',()=>{const base=fresh();const b={...base,rapportino_id:site,revisione_attesa:7,baseline:{prestazioni:[]},documento:{note:'Lavori',materiali:'Cemento',quantita_materiali:'5'},prestazioni:{nuove:[],aggiornate:[{prestazione_id:'storica'}],rimosse:['rimossa']}};const out=group.aggiungiSquadraBozzaV1(b,valid(),workers,cache,key);assert.equal(out.baseline,b.baseline);assert.equal(out.documento,b.documento);assert.equal(out.prestazioni.aggiornate,b.prestazioni.aggiornate);assert.equal(out.prestazioni.rimosse,b.prestazioni.rimosse);assert.equal(out.revisione_attesa,7);assert.equal(out.prestazioni.nuove.length,3);assert.deepEqual(Object.keys(out.prestazioni.nuove[0]),['prestazione_id','chiave_client','operaio_id','ora_inizio','ora_fine','pausa_minuti','lavoro_in_economia','variante_id'])})
test('Squadra: collisione UUID rifiutata atomicamente senza modificare bozza',()=>{const b=fresh();assert.throws(()=>group.aggiungiSquadraBozzaV1(b,valid(),workers,cache,()=>variant));assert.equal(b.prestazioni.nuove.length,0)})

test('Squadra: builder writer esistente serializza solo normali prestazioni nuove',()=>{
 const loadWriter=name=>load(path.join(__dirname,name+'.ts'),n=>n.includes('rapportinoOperai')?util:loadWriter(n.replace('./','')))
 const writer=loadWriter('salvataggioBozzaV1'),b=group.aggiungiSquadraBozzaV1(fresh(),{...valid(),lavoro_in_economia:true,variante_id:variant},workers,cache,key)
 const payload=JSON.parse(writer.creaTentativoSalvataggioV1(b,cache,key).corpo)
 assert.equal(payload.prestazioni.nuove.length,3);assert.deepEqual(payload.prestazioni.nuove,JSON.parse(JSON.stringify(b.prestazioni.nuove)))
 assert.deepEqual(Object.keys(payload.prestazioni),['nuove','aggiornate','rimosse']);assert(!JSON.stringify(payload).includes('squadra'));assert(!JSON.stringify(payload).includes('foto'))
})
