export const constructionLexicon = {
  zone: [
    'bagno',
    'cucina',
    'terrazzo',
    'facciata',
    'camera',
    'soggiorno',
    'scala',
  ],
  materiali: [
    'silicone',
    'colla',
    'rasante',
    'piastrelle',
    'cemento',
    'sabbia',
    'intonaco',
    'pittura',
  ],
  lavorazioni: [
    'posa',
    'montaggio',
    'demolizione',
    'rasatura',
    'pittura',
    'intonaco',
    'impermeabilizzazione',
  ],
  attivita: [
    'ordinare',
    'chiamare',
    'verificare',
    'completare',
    'comprare',
    'montare',
    'finire',
  ],
  dateRelative: ['oggi', 'ieri', 'domani'],
} as const
