const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript')
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',K='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',ID='cccccccc-cccc-4ccc-8ccc-cccccccccccc',D='2026-10-06',plain=x=>JSON.parse(JSON.stringify(x))
function harness(initial){let b,seq=0,active='',index=0;const states=new Map(),cache=new Map(),jsx=(type,props)=>({type,props});
 const react={useState(initial){const key=active+'/'+index++;if(!states.has(key))states.set(key,initial);return[states.get(key),v=>states.set(key,v)]}}
 function load(file){file=path.resolve(__dirname,file);if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2017}}).outputText,{exports,crypto:{randomUUID:()=> '99999999-9999-4999-8999-'+String(++seq).padStart(12,'0')},require:n=>n==='react'?react:n==='react/jsx-runtime'?{jsx,jsxs:jsx}:load(path.resolve(path.dirname(file),n)+(n.endsWith('V1')&&n.includes('Editor')?'.tsx':'.ts'))});return exports}
 const m=load('../engines/rapportini/materialiBozzaV1.ts'),save=load('../engines/rapportini/salvataggioBozzaV1.ts'),Editor=load('RapportinoMaterialiEditorV1.tsx').default;b=initial?m.ricostruisciBozzaRapportinoV2(initial):m.creaBozzaRapportinoV2(A,D)
 function nodes(n,result=[]){if(Array.isArray(n))n.forEach(x=>nodes(x,result));else if(n?.props){if(typeof n.type==='function'){active=n.props.riga?.chiave_client||'root';index=0;nodes(n.type(n.props),result)}else{result.push(n);nodes(n.props.children,result)}}return result}
 let disabled=false;const all=()=>nodes(Editor({bozza:b,onChange:v=>b=v,disabled})),click=text=>all().find(n=>n.type==='button'&&n.props.children===text).props.onClick()
 const cards=()=>all().filter(n=>n.type==='fieldset'),fields=i=>nodes(cards()[i]),input=(label,i=0)=>nodes(fields(i).find(n=>n.type==='label'&&Array.isArray(n.props.children)&&n.props.children[0]===label)).find(n=>['input','select','textarea'].includes(n.type))
 const change=(label,value,i=0)=>input(label,i).props.onChange({target:{value}}),text=()=>all().map(n=>JSON.stringify(n.props.children,(_,v)=>typeof v==='function'?undefined:v)).join('\n')
 return{m,save,all,cards,fields,input,click,change,text,value:()=>b,seq:()=>seq,setDisabled:v=>disabled=v}
}
const detalle=(versione=1)=>({versione_contratto:2,rapportino_id:ID,cantiere_id:A,data:D,revisione:2,documento:{note:'Note'},prestazioni:[],versione_materiali:versione,materiali:versione?[{materiale_id:ID,chiave_client:K,descrizione:'Cemento',unita_misura:'kg',quantita:'2.500000',costo_unitario:'12.400000',costo_totale:'31.00',note:'',revisione:1,rimossa_at:null},{materiale_id:A,chiave_client:ID,descrizione:'Rimosso',unita_misura:'cad',quantita:'1.000000',costo_unitario:null,costo_totale:null,note:'',revisione:1,rimossa_at:'2026-10-06T12:00:00Z'}]:[],riepilogo_materiali:{totale_materiali_valorizzati:versione?'31.00':'0.00',numero_materiali_da_valorizzare:0,valorizzazione_completa:true},documento_legacy_materiali:{materiali:'Vecchi mattoni',quantita_materiali:'10 sacchi'}})
const valid=h=>{h.change('Descrizione','Cemento');h.change('Quantità','2,5');h.change('U.M.','kg')}
test('M2.6 nuovo: stato vuoto, aggiunta senza autosave, identità generata una sola volta, card indipendenti',()=>{const h=harness();assert(h.text().includes('Nessun materiale inserito'));h.click('+ Aggiungi materiale');const key=h.value().materialiStrutturati.righe[0].chiave_client;assert.equal(h.seq(),1);h.all();h.all();assert.equal(h.seq(),1);valid(h);h.click('+ Aggiungi materiale');h.change('Descrizione','Cemento',1);assert.equal(h.cards().length,2);assert.equal(h.value().materialiStrutturati.righe[0].chiave_client,key);h.change('Nota materiale (facoltativa)','Solo prima');assert.equal(h.value().materialiStrutturati.righe[1].note,'');assert(!h.text().includes('microfono'))})
test('M2.6 quantità italiana e costo NULL/zero/valorizzato: anteprima dominio e totale non editabile',()=>{const h=harness();h.click('+ Aggiungi materiale');valid(h);assert(h.text().includes('Da valorizzare'));assert.equal(h.value().materialiStrutturati.righe[0].costo_unitario,null);h.change('Costo unitario (facoltativo)','0');assert(h.text().includes('Totale: € 0,00'));h.change('Costo unitario (facoltativo)','12,40');assert(h.text().includes('Totale: € 31,00'));assert(h.text().includes('Totale materiali valorizzati: € '));assert.equal(h.all().filter(n=>n.type==='output').length,1);h.change('Costo unitario (facoltativo)','');assert(h.text().includes('1 materiali da valorizzare'));assert.equal(h.value().materialiStrutturati.righe[0].costo_unitario,null)})
test('M2.6 U.M.: suggerimenti, metri lineari espliciti, altra unità libera senza conversione',()=>{const h=harness();h.click('+ Aggiungi materiale');valid(h);for(const u of ['cad','pz','kg','lt','mq','mc','ml','sacco','conf.','rotolo'])assert(h.fields(0).some(n=>n.type==='option'&&n.props.value===u));assert(h.text().includes('ml — metri lineari'));h.change('U.M.','ml');assert.equal(h.value().materialiStrutturati.righe[0].quantita,'2,5');h.change('U.M.','altra');h.change('Altra unità','bobina');assert.equal(h.value().materialiStrutturati.righe[0].unita_misura,'bobina');assert.equal(h.input('Quantità').props.inputMode,'decimal');assert.equal(h.input('Costo unitario (facoltativo)').props.inputMode,'decimal')})
test('M2.6 errori per riga: descrizione/quantità/UM/costo/note invalidi, costo assente valido',()=>{const h=harness();h.click('+ Aggiungi materiale');assert(h.text().includes('Inserisci la descrizione'));assert(h.text().includes('Inserisci l’unità di misura'));valid(h);assert.equal(h.m.erroriMaterialeBozza(h.value().materialiStrutturati.righe[0]).length,0);for(const [field,val,message] of [['Quantità','0','quantità positiva'],['Costo unitario (facoltativo)','-1','costo non negativo'],['Nota materiale (facoltativa)','x'.repeat(20001),'Nota troppo lunga']]){h.change(field,val);assert(h.text().includes(message))}})
test('M2.6 rimozione: nuova sparisce; persistente solo rimosse; tombstone invisibile',()=>{const h=harness();h.click('+ Aggiungi materiale');h.click('Rimuovi materiale');assert.equal(h.cards().length,0);assert.deepEqual(plain(h.m.deltaMaterialiBozza(h.value())),{nuove:[],aggiornate:[],rimosse:[]});const p=harness(detalle());assert.equal(p.cards().length,1);assert(!p.text().includes('Rimosso'));p.click('Rimuovi materiale');assert.deepEqual(plain(p.m.deltaMaterialiBozza(p.value())),{nuove:[],aggiornate:[],rimosse:[ID]})})
test('M2.6 storico: testi sola lettura, apertura non adotta, comando esplicito, storia resta dopo adozione',()=>{const h=harness(detalle(0));assert.equal(h.cards().length,0);assert(h.text().includes('Vecchi mattoni'));assert(h.text().includes('10 sacchi'));assert(h.text().includes('sola lettura'));assert(!h.all().some(n=>n.type==='input'||n.type==='textarea'));assert.equal(h.value().materialiStrutturati.versione_materiali,0);h.click('Usa nuova gestione materiali');assert.equal(h.value().materialiStrutturati.versione_materiali,1);assert.equal(h.cards().length,0);assert(h.text().includes('Vecchi mattoni'));assert(h.text().includes('+ Aggiungi materiale'))})
test('M2.6 disabled, accessibilità e confine condiviso senza PIN/sessione/HTTP/audio',()=>{const h=harness();h.setDisabled(true);h.click('+ Aggiungi materiale');assert.equal(h.value().materialiStrutturati.righe.length,0);const source=fs.readFileSync(path.join(__dirname,'RapportinoMaterialiEditorV1.tsx'),'utf8');assert.doesNotMatch(source,/fetch\(|PIN|sessione|SpeechRecognition|Audio|supabase|\/api\//);assert.doesNotMatch(source,/<table/);assert(source.includes('minHeight: 44'));assert(source.includes('minWidth: 0'));assert(h.all().filter(n=>n.type==='button').every(n=>n.props.type==='button'))})
test('M2.6 totale parziale e blocco builder su righe invalide',()=>{const h=harness(detalle());h.click('+ Aggiungi materiale');h.change('Descrizione','Altro',1);h.change('Quantità','1',1);h.change('U.M.','cad',1);assert.deepEqual(plain(h.m.riepilogoMaterialiBozza(h.value())),{totale_materiali_valorizzati:'31.00',numero_materiali_da_valorizzare:1,valorizzazione_completa:false});const vars={cantiere_id:A,stato:'non_caricate',varianti:[]};assert(h.save.bozzaV1Salvabile(h.value(),vars));h.change('Descrizione','',1);assert.equal(h.save.bozzaV1Salvabile(h.value(),vars),false);assert.throws(()=>h.save.creaTentativoSalvataggioV1(h.value(),vars,()=>A))})
